// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	Token     string
	UserID    uint64
	Scopes    string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID              int32
	UserID          uint64
	Quote           string
	Date            pgtype.Timestamp
	Favorite        pgtype.Int8
	Tokens          int32
	AnilistUrl      string
	DiscordUsername string
	DiscordAvatar   string
	LastUpdated     pgtype.Timestamp
}
