CREATE TABLE public.users (
  id INTEGER NOT NULL,
  user_id BIGINT NOT NULL,
  quote TEXT DEFAULT ''::TEXT NOT NULL,
  date TIMESTAMP WITHOUT TIME ZONE DEFAULT '1970-01-01 00:00:00'::TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  favorite BIGINT,
  tokens INTEGER DEFAULT 0 NOT NULL,
  anilist_url CHARACTER VARYING(255) DEFAULT ''::CHARACTER VARYING NOT NULL,
  discord_username CHARACTER VARYING(32) DEFAULT ''::CHARACTER VARYING NOT NULL UNIQUE,
  discord_avatar CHARACTER VARYING(34) DEFAULT ''::CHARACTER VARYING NOT NULL,
  last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT '1970-01-01 00:00:00'::TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE public.auth_tokens (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    scopes TEXT NOT NULL DEFAULT 'all',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX auth_tokens_user_id_idx ON auth_tokens(user_id);
