services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres
      PGDATA: "/data/postgres"

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
