// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userstore

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, userID uint64) error
	Get(ctx context.Context, userID uint64) (User, error)
	GetByAnilist(ctx context.Context, lower string) (User, error)
	GetByDiscordUsername(ctx context.Context, discordUsername string) (User, error)
	UpdateAnilistURL(ctx context.Context, arg UpdateAnilistURLParams) error
	UpdateDate(ctx context.Context, arg UpdateDateParams) error
	UpdateDiscordInfo(ctx context.Context, arg UpdateDiscordInfoParams) error
	UpdateFavorite(ctx context.Context, arg UpdateFavoriteParams) error
	UpdateQuote(ctx context.Context, arg UpdateQuoteParams) error
	UpdateTokens(ctx context.Context, arg UpdateTokensParams) (User, error)
}

var _ Querier = (*Queries)(nil)
