// Code generated by MockGen. DO NOT EDIT.
// Source: dropstore/querier.go

package mocks

import (
	context "context"
	reflect "reflect"

	dropstore "github.com/karitham/waifubot/storage/dropstore"
	gomock "go.uber.org/mock/gomock"
)

// MockDropstoreQuerier is a mock of dropstore.Querier interface.
type MockDropstoreQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockDropstoreQuerierMockRecorder
	isgomock struct{}
}

// MockDropstoreQuerierMockRecorder is the mock recorder for MockDropstoreQuerier.
type MockDropstoreQuerierMockRecorder struct {
	mock *MockDropstoreQuerier
}

// NewMockDropstoreQuerier creates a new mock instance.
func NewMockDropstoreQuerier(ctrl *gomock.Controller) *MockDropstoreQuerier {
	mock := &MockDropstoreQuerier{ctrl: ctrl}
	mock.recorder = &MockDropstoreQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDropstoreQuerier) EXPECT() *MockDropstoreQuerierMockRecorder {
	return m.recorder
}

// DeleteDrop mocks base method.
func (m *MockDropstoreQuerier) DeleteDrop(ctx context.Context, channelID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrop", ctx, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrop indicates an expected call of DeleteDrop.
func (mr *MockDropstoreQuerierMockRecorder) DeleteDrop(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrop", reflect.TypeOf((*MockDropstoreQuerier)(nil).DeleteDrop), ctx, channelID)
}

// GetDrop mocks base method.
func (m *MockDropstoreQuerier) GetDrop(ctx context.Context, channelID uint64) (dropstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrop", ctx, channelID)
	ret0, _ := ret[0].(dropstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrop indicates an expected call of GetDrop.
func (mr *MockDropstoreQuerierMockRecorder) GetDrop(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrop", reflect.TypeOf((*MockDropstoreQuerier)(nil).GetDrop), ctx, channelID)
}

// GetDropForUpdate mocks base method.
func (m *MockDropstoreQuerier) GetDropForUpdate(ctx context.Context, channelID uint64) (dropstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDropForUpdate", ctx, channelID)
	ret0, _ := ret[0].(dropstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDropForUpdate indicates an expected call of GetDropForUpdate.
func (mr *MockDropstoreQuerierMockRecorder) GetDropForUpdate(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDropForUpdate", reflect.TypeOf((*MockDropstoreQuerier)(nil).GetDropForUpdate), ctx, channelID)
}

// SetDrop mocks base method.
func (m *MockDropstoreQuerier) SetDrop(ctx context.Context, arg dropstore.SetDropParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDrop", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDrop indicates an expected call of SetDrop.
func (mr *MockDropstoreQuerierMockRecorder) SetDrop(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDrop", reflect.TypeOf((*MockDropstoreQuerier)(nil).SetDrop), ctx, arg)
}

// UpsertCharacter mocks base method.
func (m *MockDropstoreQuerier) UpsertCharacter(ctx context.Context, arg dropstore.UpsertCharacterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCharacter", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCharacter indicates an expected call of UpsertCharacter.
func (mr *MockDropstoreQuerierMockRecorder) UpsertCharacter(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCharacter", reflect.TypeOf((*MockDropstoreQuerier)(nil).UpsertCharacter), ctx, arg)
}
