// Code generated by MockGen. DO NOT EDIT.
// Source: userstore/querier.go
//
// Generated by this command:
//
//	mockgen -source=userstore/querier.go -destination=mocks/userstore_mock.go -package=mocks -mock_names=Querier=MockUserQuerier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	userstore "github.com/karitham/waifubot/storage/userstore"
	gomock "go.uber.org/mock/gomock"
)

// MockUserQuerier is a mock of Querier interface.
type MockUserQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockUserQuerierMockRecorder
	isgomock struct{}
}

// MockUserQuerierMockRecorder is the mock recorder for MockUserQuerier.
type MockUserQuerierMockRecorder struct {
	mock *MockUserQuerier
}

// NewMockUserQuerier creates a new mock instance.
func NewMockUserQuerier(ctrl *gomock.Controller) *MockUserQuerier {
	mock := &MockUserQuerier{ctrl: ctrl}
	mock.recorder = &MockUserQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQuerier) EXPECT() *MockUserQuerierMockRecorder {
	return m.recorder
}

// ConsumeTokens mocks base method.
func (m *MockUserQuerier) ConsumeTokens(ctx context.Context, arg userstore.ConsumeTokensParams) (userstore.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeTokens", ctx, arg)
	ret0, _ := ret[0].(userstore.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeTokens indicates an expected call of ConsumeTokens.
func (mr *MockUserQuerierMockRecorder) ConsumeTokens(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeTokens", reflect.TypeOf((*MockUserQuerier)(nil).ConsumeTokens), ctx, arg)
}

// Create mocks base method.
func (m *MockUserQuerier) Create(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserQuerierMockRecorder) Create(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserQuerier)(nil).Create), ctx, userID)
}

// Get mocks base method.
func (m *MockUserQuerier) Get(ctx context.Context, userID uint64) (userstore.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(userstore.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserQuerierMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserQuerier)(nil).Get), ctx, userID)
}

// GetByAnilist mocks base method.
func (m *MockUserQuerier) GetByAnilist(ctx context.Context, lower string) (userstore.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAnilist", ctx, lower)
	ret0, _ := ret[0].(userstore.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAnilist indicates an expected call of GetByAnilist.
func (mr *MockUserQuerierMockRecorder) GetByAnilist(ctx, lower any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAnilist", reflect.TypeOf((*MockUserQuerier)(nil).GetByAnilist), ctx, lower)
}

// GetByDiscordUsername mocks base method.
func (m *MockUserQuerier) GetByDiscordUsername(ctx context.Context, discordUsername string) (userstore.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDiscordUsername", ctx, discordUsername)
	ret0, _ := ret[0].(userstore.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDiscordUsername indicates an expected call of GetByDiscordUsername.
func (mr *MockUserQuerierMockRecorder) GetByDiscordUsername(ctx, discordUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDiscordUsername", reflect.TypeOf((*MockUserQuerier)(nil).GetByDiscordUsername), ctx, discordUsername)
}

// IncTokens mocks base method.
func (m *MockUserQuerier) IncTokens(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncTokens indicates an expected call of IncTokens.
func (mr *MockUserQuerierMockRecorder) IncTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncTokens", reflect.TypeOf((*MockUserQuerier)(nil).IncTokens), ctx, userID)
}

// UpdateAnilistURL mocks base method.
func (m *MockUserQuerier) UpdateAnilistURL(ctx context.Context, arg userstore.UpdateAnilistURLParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnilistURL", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnilistURL indicates an expected call of UpdateAnilistURL.
func (mr *MockUserQuerierMockRecorder) UpdateAnilistURL(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnilistURL", reflect.TypeOf((*MockUserQuerier)(nil).UpdateAnilistURL), ctx, arg)
}

// UpdateDate mocks base method.
func (m *MockUserQuerier) UpdateDate(ctx context.Context, arg userstore.UpdateDateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDate", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDate indicates an expected call of UpdateDate.
func (mr *MockUserQuerierMockRecorder) UpdateDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDate", reflect.TypeOf((*MockUserQuerier)(nil).UpdateDate), ctx, arg)
}

// UpdateDiscordInfo mocks base method.
func (m *MockUserQuerier) UpdateDiscordInfo(ctx context.Context, arg userstore.UpdateDiscordInfoParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscordInfo", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiscordInfo indicates an expected call of UpdateDiscordInfo.
func (mr *MockUserQuerierMockRecorder) UpdateDiscordInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscordInfo", reflect.TypeOf((*MockUserQuerier)(nil).UpdateDiscordInfo), ctx, arg)
}

// UpdateFavorite mocks base method.
func (m *MockUserQuerier) UpdateFavorite(ctx context.Context, arg userstore.UpdateFavoriteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavorite", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFavorite indicates an expected call of UpdateFavorite.
func (mr *MockUserQuerierMockRecorder) UpdateFavorite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavorite", reflect.TypeOf((*MockUserQuerier)(nil).UpdateFavorite), ctx, arg)
}

// UpdateQuote mocks base method.
func (m *MockUserQuerier) UpdateQuote(ctx context.Context, arg userstore.UpdateQuoteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuote", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuote indicates an expected call of UpdateQuote.
func (mr *MockUserQuerierMockRecorder) UpdateQuote(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuote", reflect.TypeOf((*MockUserQuerier)(nil).UpdateQuote), ctx, arg)
}
