// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=../mocks/wishliststore_mock.go -package=mocks -mock_names=Querier=MockWishlistQuerier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	wishliststore "github.com/karitham/waifubot/storage/wishliststore"
	gomock "go.uber.org/mock/gomock"
)

// MockWishlistQuerier is a mock of Querier interface.
type MockWishlistQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockWishlistQuerierMockRecorder
	isgomock struct{}
}

// MockWishlistQuerierMockRecorder is the mock recorder for MockWishlistQuerier.
type MockWishlistQuerierMockRecorder struct {
	mock *MockWishlistQuerier
}

// NewMockWishlistQuerier creates a new mock instance.
func NewMockWishlistQuerier(ctrl *gomock.Controller) *MockWishlistQuerier {
	mock := &MockWishlistQuerier{ctrl: ctrl}
	mock.recorder = &MockWishlistQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWishlistQuerier) EXPECT() *MockWishlistQuerierMockRecorder {
	return m.recorder
}

// AddCharacterToWishlist mocks base method.
func (m *MockWishlistQuerier) AddCharacterToWishlist(ctx context.Context, arg wishliststore.AddCharacterToWishlistParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCharacterToWishlist", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCharacterToWishlist indicates an expected call of AddCharacterToWishlist.
func (mr *MockWishlistQuerierMockRecorder) AddCharacterToWishlist(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCharacterToWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).AddCharacterToWishlist), ctx, arg)
}

// AddMultipleCharactersToWishlist mocks base method.
func (m *MockWishlistQuerier) AddMultipleCharactersToWishlist(ctx context.Context, arg wishliststore.AddMultipleCharactersToWishlistParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMultipleCharactersToWishlist", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMultipleCharactersToWishlist indicates an expected call of AddMultipleCharactersToWishlist.
func (mr *MockWishlistQuerierMockRecorder) AddMultipleCharactersToWishlist(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMultipleCharactersToWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).AddMultipleCharactersToWishlist), ctx, arg)
}

// CompareWithUser mocks base method.
func (m *MockWishlistQuerier) CompareWithUser(ctx context.Context, arg wishliststore.CompareWithUserParams) ([]wishliststore.CompareWithUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareWithUser", ctx, arg)
	ret0, _ := ret[0].([]wishliststore.CompareWithUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareWithUser indicates an expected call of CompareWithUser.
func (mr *MockWishlistQuerierMockRecorder) CompareWithUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareWithUser", reflect.TypeOf((*MockWishlistQuerier)(nil).CompareWithUser), ctx, arg)
}

// GetUserCharacterWishlist mocks base method.
func (m *MockWishlistQuerier) GetUserCharacterWishlist(ctx context.Context, userID uint64) ([]wishliststore.GetUserCharacterWishlistRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCharacterWishlist", ctx, userID)
	ret0, _ := ret[0].([]wishliststore.GetUserCharacterWishlistRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCharacterWishlist indicates an expected call of GetUserCharacterWishlist.
func (mr *MockWishlistQuerierMockRecorder) GetUserCharacterWishlist(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCharacterWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).GetUserCharacterWishlist), ctx, userID)
}

// GetWantedCharacters mocks base method.
func (m *MockWishlistQuerier) GetWantedCharacters(ctx context.Context, arg wishliststore.GetWantedCharactersParams) ([]wishliststore.GetWantedCharactersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWantedCharacters", ctx, arg)
	ret0, _ := ret[0].([]wishliststore.GetWantedCharactersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWantedCharacters indicates an expected call of GetWantedCharacters.
func (mr *MockWishlistQuerierMockRecorder) GetWantedCharacters(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWantedCharacters", reflect.TypeOf((*MockWishlistQuerier)(nil).GetWantedCharacters), ctx, arg)
}

// GetWishlistHolders mocks base method.
func (m *MockWishlistQuerier) GetWishlistHolders(ctx context.Context, arg wishliststore.GetWishlistHoldersParams) ([]wishliststore.GetWishlistHoldersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWishlistHolders", ctx, arg)
	ret0, _ := ret[0].([]wishliststore.GetWishlistHoldersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWishlistHolders indicates an expected call of GetWishlistHolders.
func (mr *MockWishlistQuerierMockRecorder) GetWishlistHolders(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWishlistHolders", reflect.TypeOf((*MockWishlistQuerier)(nil).GetWishlistHolders), ctx, arg)
}

// RemoveAllFromWishlist mocks base method.
func (m *MockWishlistQuerier) RemoveAllFromWishlist(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllFromWishlist", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllFromWishlist indicates an expected call of RemoveAllFromWishlist.
func (mr *MockWishlistQuerierMockRecorder) RemoveAllFromWishlist(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllFromWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).RemoveAllFromWishlist), ctx, userID)
}

// RemoveCharacterFromWishlist mocks base method.
func (m *MockWishlistQuerier) RemoveCharacterFromWishlist(ctx context.Context, arg wishliststore.RemoveCharacterFromWishlistParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCharacterFromWishlist", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCharacterFromWishlist indicates an expected call of RemoveCharacterFromWishlist.
func (mr *MockWishlistQuerierMockRecorder) RemoveCharacterFromWishlist(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCharacterFromWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).RemoveCharacterFromWishlist), ctx, arg)
}

// RemoveMultipleCharactersFromWishlist mocks base method.
func (m *MockWishlistQuerier) RemoveMultipleCharactersFromWishlist(ctx context.Context, arg wishliststore.RemoveMultipleCharactersFromWishlistParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMultipleCharactersFromWishlist", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMultipleCharactersFromWishlist indicates an expected call of RemoveMultipleCharactersFromWishlist.
func (mr *MockWishlistQuerierMockRecorder) RemoveMultipleCharactersFromWishlist(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMultipleCharactersFromWishlist", reflect.TypeOf((*MockWishlistQuerier)(nil).RemoveMultipleCharactersFromWishlist), ctx, arg)
}
