// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package anilist

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// Media type enum, anime or manga.
type MediaType string

const (
	// Japanese Anime
	MediaTypeAnime MediaType = "ANIME"
	// Asian comic
	MediaTypeManga MediaType = "MANGA"
)

// __characterInput is used internally by genqlient
type __characterInput struct {
	Name string `json:"name"`
}

// GetName returns __characterInput.Name, and is useful for accessing the field via an interface.
func (v *__characterInput) GetName() string { return v.Name }

// __charactersRandomInput is used internally by genqlient
type __charactersRandomInput struct {
	PageNumber int64   `json:"pageNumber"`
	Not_in     []int64 `json:"not_in"`
}

// GetPageNumber returns __charactersRandomInput.PageNumber, and is useful for accessing the field via an interface.
func (v *__charactersRandomInput) GetPageNumber() int64 { return v.PageNumber }

// GetNot_in returns __charactersRandomInput.Not_in, and is useful for accessing the field via an interface.
func (v *__charactersRandomInput) GetNot_in() []int64 { return v.Not_in }

// __mediaInput is used internally by genqlient
type __mediaInput struct {
	Name string    `json:"name"`
	Typ  MediaType `json:"typ"`
}

// GetName returns __mediaInput.Name, and is useful for accessing the field via an interface.
func (v *__mediaInput) GetName() string { return v.Name }

// GetTyp returns __mediaInput.Typ, and is useful for accessing the field via an interface.
func (v *__mediaInput) GetTyp() MediaType { return v.Typ }

// __userInput is used internally by genqlient
type __userInput struct {
	Name string `json:"name"`
}

// GetName returns __userInput.Name, and is useful for accessing the field via an interface.
func (v *__userInput) GetName() string { return v.Name }

// characterPage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type characterPage struct {
	Characters []characterPageCharactersCharacter `json:"characters"`
}

// GetCharacters returns characterPage.Characters, and is useful for accessing the field via an interface.
func (v *characterPage) GetCharacters() []characterPageCharactersCharacter { return v.Characters }

// characterPageCharactersCharacter includes the requested fields of the GraphQL type Character.
// The GraphQL type's documentation follows.
//
// A character that features in an anime or manga
type characterPageCharactersCharacter struct {
	// The id of the character
	Id int64 `json:"id"`
	// The names of the character
	Name characterPageCharactersCharacterName `json:"name"`
	// A general description of the character
	Description string `json:"description"`
	// The url for the character page on the AniList website
	SiteUrl string `json:"siteUrl"`
	// Character images
	Image characterPageCharactersCharacterImage `json:"image"`
}

// GetId returns characterPageCharactersCharacter.Id, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacter) GetId() int64 { return v.Id }

// GetName returns characterPageCharactersCharacter.Name, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacter) GetName() characterPageCharactersCharacterName {
	return v.Name
}

// GetDescription returns characterPageCharactersCharacter.Description, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacter) GetDescription() string { return v.Description }

// GetSiteUrl returns characterPageCharactersCharacter.SiteUrl, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacter) GetSiteUrl() string { return v.SiteUrl }

// GetImage returns characterPageCharactersCharacter.Image, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacter) GetImage() characterPageCharactersCharacterImage {
	return v.Image
}

// characterPageCharactersCharacterImage includes the requested fields of the GraphQL type CharacterImage.
type characterPageCharactersCharacterImage struct {
	// The character's image of media at its largest size
	Large string `json:"large"`
}

// GetLarge returns characterPageCharactersCharacterImage.Large, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacterImage) GetLarge() string { return v.Large }

// characterPageCharactersCharacterName includes the requested fields of the GraphQL type CharacterName.
// The GraphQL type's documentation follows.
//
// The names of the character
type characterPageCharactersCharacterName struct {
	// The character's first and last name
	Full string `json:"full"`
}

// GetFull returns characterPageCharactersCharacterName.Full, and is useful for accessing the field via an interface.
func (v *characterPageCharactersCharacterName) GetFull() string { return v.Full }

// characterResponse is returned by character on success.
type characterResponse struct {
	Page characterPage `json:"Page"`
}

// GetPage returns characterResponse.Page, and is useful for accessing the field via an interface.
func (v *characterResponse) GetPage() characterPage { return v.Page }

// charactersRandomPage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type charactersRandomPage struct {
	Characters []charactersRandomPageCharactersCharacter `json:"characters"`
}

// GetCharacters returns charactersRandomPage.Characters, and is useful for accessing the field via an interface.
func (v *charactersRandomPage) GetCharacters() []charactersRandomPageCharactersCharacter {
	return v.Characters
}

// charactersRandomPageCharactersCharacter includes the requested fields of the GraphQL type Character.
// The GraphQL type's documentation follows.
//
// A character that features in an anime or manga
type charactersRandomPageCharactersCharacter struct {
	// The id of the character
	Id int64 `json:"id"`
	// The url for the character page on the AniList website
	SiteUrl string `json:"siteUrl"`
	// Character images
	Image charactersRandomPageCharactersCharacterImage `json:"image"`
	// The names of the character
	Name charactersRandomPageCharactersCharacterName `json:"name"`
	// Media that includes the character
	Media charactersRandomPageCharactersCharacterMediaMediaConnection `json:"media"`
}

// GetId returns charactersRandomPageCharactersCharacter.Id, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacter) GetId() int64 { return v.Id }

// GetSiteUrl returns charactersRandomPageCharactersCharacter.SiteUrl, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacter) GetSiteUrl() string { return v.SiteUrl }

// GetImage returns charactersRandomPageCharactersCharacter.Image, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacter) GetImage() charactersRandomPageCharactersCharacterImage {
	return v.Image
}

// GetName returns charactersRandomPageCharactersCharacter.Name, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacter) GetName() charactersRandomPageCharactersCharacterName {
	return v.Name
}

// GetMedia returns charactersRandomPageCharactersCharacter.Media, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacter) GetMedia() charactersRandomPageCharactersCharacterMediaMediaConnection {
	return v.Media
}

// charactersRandomPageCharactersCharacterImage includes the requested fields of the GraphQL type CharacterImage.
type charactersRandomPageCharactersCharacterImage struct {
	// The character's image of media at its largest size
	Large string `json:"large"`
}

// GetLarge returns charactersRandomPageCharactersCharacterImage.Large, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacterImage) GetLarge() string { return v.Large }

// charactersRandomPageCharactersCharacterMediaMediaConnection includes the requested fields of the GraphQL type MediaConnection.
type charactersRandomPageCharactersCharacterMediaMediaConnection struct {
	Nodes []charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia `json:"nodes"`
}

// GetNodes returns charactersRandomPageCharactersCharacterMediaMediaConnection.Nodes, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacterMediaMediaConnection) GetNodes() []charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia {
	return v.Nodes
}

// charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia struct {
	// The official titles of the media in various languages
	Title charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle `json:"title"`
}

// GetTitle returns charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia.Title, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMedia) GetTitle() charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle {
	return v.Title
}

// charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacterMediaMediaConnectionNodesMediaTitle) GetRomaji() string {
	return v.Romaji
}

// charactersRandomPageCharactersCharacterName includes the requested fields of the GraphQL type CharacterName.
// The GraphQL type's documentation follows.
//
// The names of the character
type charactersRandomPageCharactersCharacterName struct {
	// The character's first and last name
	Full string `json:"full"`
}

// GetFull returns charactersRandomPageCharactersCharacterName.Full, and is useful for accessing the field via an interface.
func (v *charactersRandomPageCharactersCharacterName) GetFull() string { return v.Full }

// charactersRandomResponse is returned by charactersRandom on success.
type charactersRandomResponse struct {
	Page charactersRandomPage `json:"Page"`
}

// GetPage returns charactersRandomResponse.Page, and is useful for accessing the field via an interface.
func (v *charactersRandomResponse) GetPage() charactersRandomPage { return v.Page }

// mediaPage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type mediaPage struct {
	Media []mediaPageMedia `json:"media"`
}

// GetMedia returns mediaPage.Media, and is useful for accessing the field via an interface.
func (v *mediaPage) GetMedia() []mediaPageMedia { return v.Media }

// mediaPageMedia includes the requested fields of the GraphQL type Media.
// The GraphQL type's documentation follows.
//
// Anime or Manga
type mediaPageMedia struct {
	// The id of the media
	Id int64 `json:"id"`
	// The official titles of the media in various languages
	Title mediaPageMediaTitle `json:"title"`
	// Short description of the media's story and characters
	Description string `json:"description"`
	// The url for the media page on the AniList website
	SiteUrl string `json:"siteUrl"`
	// The cover images of the media
	CoverImage mediaPageMediaCoverImage `json:"coverImage"`
	// The banner image of the media
	BannerImage string `json:"bannerImage"`
}

// GetId returns mediaPageMedia.Id, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetId() int64 { return v.Id }

// GetTitle returns mediaPageMedia.Title, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetTitle() mediaPageMediaTitle { return v.Title }

// GetDescription returns mediaPageMedia.Description, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetDescription() string { return v.Description }

// GetSiteUrl returns mediaPageMedia.SiteUrl, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetSiteUrl() string { return v.SiteUrl }

// GetCoverImage returns mediaPageMedia.CoverImage, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetCoverImage() mediaPageMediaCoverImage { return v.CoverImage }

// GetBannerImage returns mediaPageMedia.BannerImage, and is useful for accessing the field via an interface.
func (v *mediaPageMedia) GetBannerImage() string { return v.BannerImage }

// mediaPageMediaCoverImage includes the requested fields of the GraphQL type MediaCoverImage.
type mediaPageMediaCoverImage struct {
	// The cover image url of the media at a large size
	Large string `json:"large"`
	// Average #hex color of cover image
	Color string `json:"color"`
}

// GetLarge returns mediaPageMediaCoverImage.Large, and is useful for accessing the field via an interface.
func (v *mediaPageMediaCoverImage) GetLarge() string { return v.Large }

// GetColor returns mediaPageMediaCoverImage.Color, and is useful for accessing the field via an interface.
func (v *mediaPageMediaCoverImage) GetColor() string { return v.Color }

// mediaPageMediaTitle includes the requested fields of the GraphQL type MediaTitle.
// The GraphQL type's documentation follows.
//
// The official titles of the media in various languages
type mediaPageMediaTitle struct {
	// The romanization of the native language title
	Romaji string `json:"romaji"`
}

// GetRomaji returns mediaPageMediaTitle.Romaji, and is useful for accessing the field via an interface.
func (v *mediaPageMediaTitle) GetRomaji() string { return v.Romaji }

// mediaResponse is returned by media on success.
type mediaResponse struct {
	Page mediaPage `json:"Page"`
}

// GetPage returns mediaResponse.Page, and is useful for accessing the field via an interface.
func (v *mediaResponse) GetPage() mediaPage { return v.Page }

// userPage includes the requested fields of the GraphQL type Page.
// The GraphQL type's documentation follows.
//
// Page of data
type userPage struct {
	Users []userPageUsersUser `json:"users"`
}

// GetUsers returns userPage.Users, and is useful for accessing the field via an interface.
func (v *userPage) GetUsers() []userPageUsersUser { return v.Users }

// userPageUsersUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user
type userPageUsersUser struct {
	// The id of the user
	Id int64 `json:"id"`
	// The name of the user
	Name string `json:"name"`
	// The bio written by user (Markdown)
	About string `json:"about"`
	// The url for the user page on the AniList website
	SiteUrl string `json:"siteUrl"`
	// The user's avatar images
	Avatar userPageUsersUserAvatar `json:"avatar"`
	// The user's banner images
	BannerImage string `json:"bannerImage"`
}

// GetId returns userPageUsersUser.Id, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetId() int64 { return v.Id }

// GetName returns userPageUsersUser.Name, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetName() string { return v.Name }

// GetAbout returns userPageUsersUser.About, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetAbout() string { return v.About }

// GetSiteUrl returns userPageUsersUser.SiteUrl, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetSiteUrl() string { return v.SiteUrl }

// GetAvatar returns userPageUsersUser.Avatar, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetAvatar() userPageUsersUserAvatar { return v.Avatar }

// GetBannerImage returns userPageUsersUser.BannerImage, and is useful for accessing the field via an interface.
func (v *userPageUsersUser) GetBannerImage() string { return v.BannerImage }

// userPageUsersUserAvatar includes the requested fields of the GraphQL type UserAvatar.
// The GraphQL type's documentation follows.
//
// A user's avatars
type userPageUsersUserAvatar struct {
	// The avatar of user at its largest size
	Large string `json:"large"`
}

// GetLarge returns userPageUsersUserAvatar.Large, and is useful for accessing the field via an interface.
func (v *userPageUsersUserAvatar) GetLarge() string { return v.Large }

// userResponse is returned by user on success.
type userResponse struct {
	Page userPage `json:"Page"`
}

// GetPage returns userResponse.Page, and is useful for accessing the field via an interface.
func (v *userResponse) GetPage() userPage { return v.Page }

func character(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*characterResponse, error) {
	req := &graphql.Request{
		OpName: "character",
		Query: `
query character ($name: String) {
	Page(page: 1, perPage: 3) {
		characters(search: $name) {
			id
			name {
				full
			}
			description
			siteUrl
			image {
				large
			}
		}
	}
}
`,
		Variables: &__characterInput{
			Name: name,
		},
	}
	var err error

	var data characterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func charactersRandom(
	ctx context.Context,
	client graphql.Client,
	pageNumber int64,
	not_in []int64,
) (*charactersRandomResponse, error) {
	req := &graphql.Request{
		OpName: "charactersRandom",
		Query: `
query charactersRandom ($pageNumber: Int, $not_in: [Int]) {
	Page(perPage: 1, page: $pageNumber) {
		characters(sort: FAVOURITES_DESC, id_not_in: $not_in) {
			id
			siteUrl
			image {
				large
			}
			name {
				full
			}
			media(perPage: 1, sort: POPULARITY_DESC) {
				nodes {
					title {
						romaji
					}
				}
			}
		}
	}
}
`,
		Variables: &__charactersRandomInput{
			PageNumber: pageNumber,
			Not_in:     not_in,
		},
	}
	var err error

	var data charactersRandomResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func media(
	ctx context.Context,
	client graphql.Client,
	name string,
	typ MediaType,
) (*mediaResponse, error) {
	req := &graphql.Request{
		OpName: "media",
		Query: `
query media ($name: String, $typ: MediaType) {
	Page(page: 1, perPage: 3) {
		media(search: $name, type: $typ) {
			id
			title {
				romaji
			}
			description
			siteUrl
			coverImage {
				large
				color
			}
			bannerImage
		}
	}
}
`,
		Variables: &__mediaInput{
			Name: name,
			Typ:  typ,
		},
	}
	var err error

	var data mediaResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func user(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*userResponse, error) {
	req := &graphql.Request{
		OpName: "user",
		Query: `
query user ($name: String) {
	Page(page: 1, perPage: 3) {
		users(search: $name) {
			id
			name
			about
			siteUrl
			avatar {
				large
			}
			bannerImage
		}
	}
}
`,
		Variables: &__userInput{
			Name: name,
		},
	}
	var err error

	var data userResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
