// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddWishlistCharacters implements addWishlistCharacters operation.
	//
	// Add characters to wishlist.
	//
	// POST /api/v1/wishlist/characters
	AddWishlistCharacters(ctx context.Context, req *WishlistCharacterAdd) (AddWishlistCharactersRes, error)
	// ClearWishlist implements clearWishlist operation.
	//
	// Clear entire wishlist.
	//
	// DELETE /api/v1/wishlist
	ClearWishlist(ctx context.Context) (ClearWishlistRes, error)
	// FindUser implements findUser operation.
	//
	// Find a user by their Anilist URL or Discord username. Query parameters are mutually exclusive.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /user/find
	FindUser(ctx context.Context, params FindUserParams) (FindUserRes, error)
	// FindUserV1 implements findUserV1 operation.
	//
	// Find a user by their Anilist URL or Discord username. Query parameters are mutually exclusive.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /api/v1/user/find
	FindUserV1(ctx context.Context, params FindUserV1Params) (FindUserV1Res, error)
	// GetCollectionV1 implements getCollectionV1 operation.
	//
	// Retrieve a user's character collection.
	//
	// GET /api/v1/collection/{userID}
	GetCollectionV1(ctx context.Context, params GetCollectionV1Params) (GetCollectionV1Res, error)
	// GetProfileV1 implements getProfileV1 operation.
	//
	// Retrieve a user's profile information and favorite character.
	//
	// GET /api/v1/profile/{userID}
	GetProfileV1(ctx context.Context, params GetProfileV1Params) (GetProfileV1Res, error)
	// GetUser implements getUser operation.
	//
	// Retrieve a user's complete profile including user info, collection, and favorite character.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /user/{userID}
	GetUser(ctx context.Context, params GetUserParams) (GetUserRes, error)
	// GetUserV1 implements getUserV1 operation.
	//
	// Retrieve a user's complete profile including user info, collection, and favorite character.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /api/v1/user/{userID}
	GetUserV1(ctx context.Context, params GetUserV1Params) (GetUserV1Res, error)
	// GetWishlist implements getWishlist operation.
	//
	// Retrieve a user's wishlist of characters.
	//
	// GET /api/v1/wishlist/{userID}
	GetWishlist(ctx context.Context, params GetWishlistParams) (GetWishlistRes, error)
	// RemoveWishlistCharacters implements removeWishlistCharacters operation.
	//
	// Remove characters from wishlist.
	//
	// DELETE /api/v1/wishlist/characters
	RemoveWishlistCharacters(ctx context.Context, req *WishlistCharacterRemove) (RemoveWishlistCharactersRes, error)
	// UpdateFavorite implements updateFavorite operation.
	//
	// Set favorite character.
	//
	// PUT /api/v1/profile/favorite
	UpdateFavorite(ctx context.Context, req *FavoriteUpdate) (UpdateFavoriteRes, error)
	// UpdateProfile implements updateProfile operation.
	//
	// Update authenticated user's profile.
	//
	// PUT /api/v1/profile
	UpdateProfile(ctx context.Context, req *ProfileUpdate) (UpdateProfileRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
