// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// FindUser implements findUser operation.
//
// Find a user by their Anilist URL or Discord username. Query parameters are mutually exclusive.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /user/find
func (UnimplementedHandler) FindUser(ctx context.Context, params FindUserParams) (r FindUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// FindUserV1 implements findUserV1 operation.
//
// Find a user by their Anilist URL or Discord username. Query parameters are mutually exclusive.
//
// GET /api/v1/user/find
func (UnimplementedHandler) FindUserV1(ctx context.Context, params FindUserV1Params) (r FindUserV1Res, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Retrieve a user's complete profile including user info, collection, and favorite character.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /user/{userID}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r GetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserV1 implements getUserV1 operation.
//
// Retrieve a user's complete profile including user info, collection, and favorite character.
//
// GET /api/v1/user/{userID}
func (UnimplementedHandler) GetUserV1(ctx context.Context, params GetUserV1Params) (r GetUserV1Res, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWishlist implements getWishlist operation.
//
// Retrieve a user's wishlist of characters.
//
// GET /api/v1/wishlist/{userID}
func (UnimplementedHandler) GetWishlist(ctx context.Context, params GetWishlistParams) (r GetWishlistRes, _ error) {
	return r, ht.ErrNotImplemented
}
