// Code generated by ogen, DO NOT EDIT.
package api

type FindUserRes interface {
	findUserRes()
}

type FindUserV1Res interface {
	findUserV1Res()
}

type GetUserRes interface {
	getUserRes()
}

type GetUserV1Res interface {
	getUserV1Res()
}

type GetWishlistRes interface {
	getWishlistRes()
}
