// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/url"
	"time"

	"github.com/go-faster/errors"
)

func (s *InternalErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Character information.
// Ref: #/components/schemas/Character
type Character struct {
	// Date the character was added.
	Date time.Time `json:"date"`
	// Character name.
	Name string `json:"name"`
	// Character image URL.
	Image string `json:"image"`
	// Character source type.
	Type CharacterType `json:"type"`
	// Character ID.
	ID int64 `json:"id"`
}

// GetDate returns the value of Date.
func (s *Character) GetDate() time.Time {
	return s.Date
}

// GetName returns the value of Name.
func (s *Character) GetName() string {
	return s.Name
}

// GetImage returns the value of Image.
func (s *Character) GetImage() string {
	return s.Image
}

// GetType returns the value of Type.
func (s *Character) GetType() CharacterType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Character) GetID() int64 {
	return s.ID
}

// SetDate sets the value of Date.
func (s *Character) SetDate(val time.Time) {
	s.Date = val
}

// SetName sets the value of Name.
func (s *Character) SetName(val string) {
	s.Name = val
}

// SetImage sets the value of Image.
func (s *Character) SetImage(val string) {
	s.Image = val
}

// SetType sets the value of Type.
func (s *Character) SetType(val CharacterType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Character) SetID(val int64) {
	s.ID = val
}

func (*Character) getUserFavoriteRes() {}

// Character source type.
type CharacterType string

const (
	CharacterTypeROLL  CharacterType = "ROLL"
	CharacterTypeCLAIM CharacterType = "CLAIM"
	CharacterTypeGIVE  CharacterType = "GIVE"
	CharacterTypeOLD   CharacterType = "OLD"
)

// AllValues returns all CharacterType values.
func (CharacterType) AllValues() []CharacterType {
	return []CharacterType{
		CharacterTypeROLL,
		CharacterTypeCLAIM,
		CharacterTypeGIVE,
		CharacterTypeOLD,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CharacterType) MarshalText() ([]byte, error) {
	switch s {
	case CharacterTypeROLL:
		return []byte(s), nil
	case CharacterTypeCLAIM:
		return []byte(s), nil
	case CharacterTypeGIVE:
		return []byte(s), nil
	case CharacterTypeOLD:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CharacterType) UnmarshalText(data []byte) error {
	switch CharacterType(data) {
	case CharacterTypeROLL:
		*s = CharacterTypeROLL
		return nil
	case CharacterTypeCLAIM:
		*s = CharacterTypeCLAIM
		return nil
	case CharacterTypeGIVE:
		*s = CharacterTypeGIVE
		return nil
	case CharacterTypeOLD:
		*s = CharacterTypeOLD
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// User's character collection.
// Ref: #/components/schemas/Collection
type Collection struct {
	// List of characters in the collection.
	Characters []Character `json:"characters"`
	// Total number of characters in the collection across all pages.
	Total int `json:"total"`
	// Token for retrieving the next page of results.
	NextPageToken OptString `json:"next_page_token"`
}

// GetCharacters returns the value of Characters.
func (s *Collection) GetCharacters() []Character {
	return s.Characters
}

// GetTotal returns the value of Total.
func (s *Collection) GetTotal() int {
	return s.Total
}

// GetNextPageToken returns the value of NextPageToken.
func (s *Collection) GetNextPageToken() OptString {
	return s.NextPageToken
}

// SetCharacters sets the value of Characters.
func (s *Collection) SetCharacters(val []Character) {
	s.Characters = val
}

// SetTotal sets the value of Total.
func (s *Collection) SetTotal(val int) {
	s.Total = val
}

// SetNextPageToken sets the value of NextPageToken.
func (s *Collection) SetNextPageToken(val OptString) {
	s.NextPageToken = val
}

func (*Collection) getUserCollectionRes() {}

type Direction string

const (
	DirectionAsc  Direction = "asc"
	DirectionDesc Direction = "desc"
)

// AllValues returns all Direction values.
func (Direction) AllValues() []Direction {
	return []Direction{
		DirectionAsc,
		DirectionDesc,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Direction) MarshalText() ([]byte, error) {
	switch s {
	case DirectionAsc:
		return []byte(s), nil
	case DirectionDesc:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Direction) UnmarshalText(data []byte) error {
	switch Direction(data) {
	case DirectionAsc:
		*s = DirectionAsc
		return nil
	case DirectionDesc:
		*s = DirectionDesc
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Standard error response.
// Ref: #/components/schemas/Error
type Error struct {
	// Error message.
	Message string `json:"message"`
	// Error code.
	ErrorCode string `json:"error_code"`
	// HTTP status code.
	StatusCode int `json:"status_code"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() string {
	return s.ErrorCode
}

// GetStatusCode returns the value of StatusCode.
func (s *Error) GetStatusCode() int {
	return s.StatusCode
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val string) {
	s.ErrorCode = val
}

// SetStatusCode sets the value of StatusCode.
func (s *Error) SetStatusCode(val int) {
	s.StatusCode = val
}

type FindUserLegacyBadRequest Error

func (*FindUserLegacyBadRequest) findUserLegacyRes() {}

type FindUserLegacyForbidden Error

func (*FindUserLegacyForbidden) findUserLegacyRes() {}

type FindUserLegacyNotFound Error

func (*FindUserLegacyNotFound) findUserLegacyRes() {}

type FindUserLegacyUnauthorized Error

func (*FindUserLegacyUnauthorized) findUserLegacyRes() {}

type GetUserBadRequest Error

func (*GetUserBadRequest) getUserRes() {}

type GetUserCollectionBadRequest Error

func (*GetUserCollectionBadRequest) getUserCollectionRes() {}

type GetUserCollectionForbidden Error

func (*GetUserCollectionForbidden) getUserCollectionRes() {}

type GetUserCollectionNotFound Error

func (*GetUserCollectionNotFound) getUserCollectionRes() {}

type GetUserCollectionUnauthorized Error

func (*GetUserCollectionUnauthorized) getUserCollectionRes() {}

type GetUserFavoriteBadRequest Error

func (*GetUserFavoriteBadRequest) getUserFavoriteRes() {}

type GetUserFavoriteForbidden Error

func (*GetUserFavoriteForbidden) getUserFavoriteRes() {}

// GetUserFavoriteNoContent is response for GetUserFavorite operation.
type GetUserFavoriteNoContent struct{}

func (*GetUserFavoriteNoContent) getUserFavoriteRes() {}

type GetUserFavoriteNotFound Error

func (*GetUserFavoriteNotFound) getUserFavoriteRes() {}

type GetUserFavoriteUnauthorized Error

func (*GetUserFavoriteUnauthorized) getUserFavoriteRes() {}

type GetUserForbidden Error

func (*GetUserForbidden) getUserRes() {}

type GetUserLegacyBadRequest Error

func (*GetUserLegacyBadRequest) getUserLegacyRes() {}

type GetUserLegacyForbidden Error

func (*GetUserLegacyForbidden) getUserLegacyRes() {}

type GetUserLegacyNotFound Error

func (*GetUserLegacyNotFound) getUserLegacyRes() {}

type GetUserLegacyUnauthorized Error

func (*GetUserLegacyUnauthorized) getUserLegacyRes() {}

type GetUserNotFound Error

func (*GetUserNotFound) getUserRes() {}

type GetUserUnauthorized Error

func (*GetUserUnauthorized) getUserRes() {}

type GetUserWishlistBadRequest Error

func (*GetUserWishlistBadRequest) getUserWishlistRes() {}

type GetUserWishlistForbidden Error

func (*GetUserWishlistForbidden) getUserWishlistRes() {}

type GetUserWishlistNotFound Error

func (*GetUserWishlistNotFound) getUserWishlistRes() {}

type GetUserWishlistUnauthorized Error

func (*GetUserWishlistUnauthorized) getUserWishlistRes() {}

// InternalErrorStatusCode wraps Error with StatusCode.
type InternalErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*InternalErrorStatusCode) findUserLegacyRes()    {}
func (*InternalErrorStatusCode) getUserCollectionRes() {}
func (*InternalErrorStatusCode) getUserFavoriteRes()   {}
func (*InternalErrorStatusCode) getUserLegacyRes()     {}
func (*InternalErrorStatusCode) getUserRes()           {}
func (*InternalErrorStatusCode) getUserWishlistRes()   {}
func (*InternalErrorStatusCode) listUsersRes()         {}

type ListUsersBadRequest Error

func (*ListUsersBadRequest) listUsersRes() {}

type ListUsersForbidden Error

func (*ListUsersForbidden) listUsersRes() {}

type ListUsersUnauthorized Error

func (*ListUsersUnauthorized) listUsersRes() {}

// NewOptCharacter returns new OptCharacter with value set to v.
func NewOptCharacter(v Character) OptCharacter {
	return OptCharacter{
		Value: v,
		Set:   true,
	}
}

// OptCharacter is optional Character.
type OptCharacter struct {
	Value Character
	Set   bool
}

// IsSet returns true if OptCharacter was set.
func (o OptCharacter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCharacter) Reset() {
	var v Character
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCharacter) SetTo(v Character) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCharacter) Get() (v Character, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCharacter) Or(d Character) Character {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDirection returns new OptDirection with value set to v.
func NewOptDirection(v Direction) OptDirection {
	return OptDirection{
		Value: v,
		Set:   true,
	}
}

// OptDirection is optional Direction.
type OptDirection struct {
	Value Direction
	Set   bool
}

// IsSet returns true if OptDirection was set.
func (o OptDirection) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDirection) Reset() {
	var v Direction
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDirection) SetTo(v Direction) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDirection) Get() (v Direction, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDirection) Or(d Direction) Direction {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderBy returns new OptOrderBy with value set to v.
func NewOptOrderBy(v OrderBy) OptOrderBy {
	return OptOrderBy{
		Value: v,
		Set:   true,
	}
}

// OptOrderBy is optional OrderBy.
type OptOrderBy struct {
	Value OrderBy
	Set   bool
}

// IsSet returns true if OptOrderBy was set.
func (o OptOrderBy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderBy) Reset() {
	var v OrderBy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderBy) SetTo(v OrderBy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderBy) Get() (v OrderBy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderBy) Or(d OrderBy) OrderBy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type OrderBy string

const (
	OrderByDate      OrderBy = "date"
	OrderByName      OrderBy = "name"
	OrderByAnilistID OrderBy = "anilist_id"
)

// AllValues returns all OrderBy values.
func (OrderBy) AllValues() []OrderBy {
	return []OrderBy{
		OrderByDate,
		OrderByName,
		OrderByAnilistID,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderBy) MarshalText() ([]byte, error) {
	switch s {
	case OrderByDate:
		return []byte(s), nil
	case OrderByName:
		return []byte(s), nil
	case OrderByAnilistID:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderBy) UnmarshalText(data []byte) error {
	switch OrderBy(data) {
	case OrderByDate:
		*s = OrderByDate
		return nil
	case OrderByName:
		*s = OrderByName
		return nil
	case OrderByAnilistID:
		*s = OrderByAnilistID
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Complete user profile including user information, collection, and favorite character (deprecated).
// Ref: #/components/schemas/Profile
type Profile struct {
	// User ID.
	ID string `json:"id"`
	// User's personal quote.
	Quote OptString `json:"quote"`
	// User's token balance.
	Tokens int32 `json:"tokens"`
	// Anilist user URL.
	AnilistURL OptString `json:"anilist_url"`
	// Discord username.
	DiscordUsername string `json:"discord_username"`
	// Discord avatar URL.
	DiscordAvatar OptString `json:"discord_avatar"`
	// User's favorite character (may be null if no favorite set).
	Favorite OptCharacter `json:"favorite"`
	// List of characters in user's collection.
	Waifus []Character `json:"waifus"`
}

// GetID returns the value of ID.
func (s *Profile) GetID() string {
	return s.ID
}

// GetQuote returns the value of Quote.
func (s *Profile) GetQuote() OptString {
	return s.Quote
}

// GetTokens returns the value of Tokens.
func (s *Profile) GetTokens() int32 {
	return s.Tokens
}

// GetAnilistURL returns the value of AnilistURL.
func (s *Profile) GetAnilistURL() OptString {
	return s.AnilistURL
}

// GetDiscordUsername returns the value of DiscordUsername.
func (s *Profile) GetDiscordUsername() string {
	return s.DiscordUsername
}

// GetDiscordAvatar returns the value of DiscordAvatar.
func (s *Profile) GetDiscordAvatar() OptString {
	return s.DiscordAvatar
}

// GetFavorite returns the value of Favorite.
func (s *Profile) GetFavorite() OptCharacter {
	return s.Favorite
}

// GetWaifus returns the value of Waifus.
func (s *Profile) GetWaifus() []Character {
	return s.Waifus
}

// SetID sets the value of ID.
func (s *Profile) SetID(val string) {
	s.ID = val
}

// SetQuote sets the value of Quote.
func (s *Profile) SetQuote(val OptString) {
	s.Quote = val
}

// SetTokens sets the value of Tokens.
func (s *Profile) SetTokens(val int32) {
	s.Tokens = val
}

// SetAnilistURL sets the value of AnilistURL.
func (s *Profile) SetAnilistURL(val OptString) {
	s.AnilistURL = val
}

// SetDiscordUsername sets the value of DiscordUsername.
func (s *Profile) SetDiscordUsername(val string) {
	s.DiscordUsername = val
}

// SetDiscordAvatar sets the value of DiscordAvatar.
func (s *Profile) SetDiscordAvatar(val OptString) {
	s.DiscordAvatar = val
}

// SetFavorite sets the value of Favorite.
func (s *Profile) SetFavorite(val OptCharacter) {
	s.Favorite = val
}

// SetWaifus sets the value of Waifus.
func (s *Profile) SetWaifus(val []Character) {
	s.Waifus = val
}

func (*Profile) getUserLegacyRes() {}

// User resource containing profile metadata.
// Ref: #/components/schemas/User
type User struct {
	// Resource name.
	Name string `json:"name"`
	// User ID.
	ID string `json:"id"`
	// User's personal quote.
	Quote OptString `json:"quote"`
	// User's token balance.
	Tokens int32 `json:"tokens"`
	// Anilist user URL.
	AnilistURL OptString `json:"anilist_url"`
	// Discord username.
	DiscordUsername string `json:"discord_username"`
	// Discord avatar URL.
	DiscordAvatar OptString `json:"discord_avatar"`
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetQuote returns the value of Quote.
func (s *User) GetQuote() OptString {
	return s.Quote
}

// GetTokens returns the value of Tokens.
func (s *User) GetTokens() int32 {
	return s.Tokens
}

// GetAnilistURL returns the value of AnilistURL.
func (s *User) GetAnilistURL() OptString {
	return s.AnilistURL
}

// GetDiscordUsername returns the value of DiscordUsername.
func (s *User) GetDiscordUsername() string {
	return s.DiscordUsername
}

// GetDiscordAvatar returns the value of DiscordAvatar.
func (s *User) GetDiscordAvatar() OptString {
	return s.DiscordAvatar
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetQuote sets the value of Quote.
func (s *User) SetQuote(val OptString) {
	s.Quote = val
}

// SetTokens sets the value of Tokens.
func (s *User) SetTokens(val int32) {
	s.Tokens = val
}

// SetAnilistURL sets the value of AnilistURL.
func (s *User) SetAnilistURL(val OptString) {
	s.AnilistURL = val
}

// SetDiscordUsername sets the value of DiscordUsername.
func (s *User) SetDiscordUsername(val string) {
	s.DiscordUsername = val
}

// SetDiscordAvatar sets the value of DiscordAvatar.
func (s *User) SetDiscordAvatar(val OptString) {
	s.DiscordAvatar = val
}

func (*User) getUserRes() {}

// Response containing only the user ID.
// Ref: #/components/schemas/UserIdResponse
type UserIdResponse struct {
	// User ID.
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *UserIdResponse) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *UserIdResponse) SetID(val string) {
	s.ID = val
}

func (*UserIdResponse) findUserLegacyRes() {}

// List of users with pagination info.
// Ref: #/components/schemas/UserList
type UserList struct {
	// List of users matching the query.
	Users []User `json:"users"`
	// Total number of users matching the query.
	Total int `json:"total"`
	// Token for retrieving the next page of results. Omitted if no more pages.
	NextPageToken OptString `json:"next_page_token"`
}

// GetUsers returns the value of Users.
func (s *UserList) GetUsers() []User {
	return s.Users
}

// GetTotal returns the value of Total.
func (s *UserList) GetTotal() int {
	return s.Total
}

// GetNextPageToken returns the value of NextPageToken.
func (s *UserList) GetNextPageToken() OptString {
	return s.NextPageToken
}

// SetUsers sets the value of Users.
func (s *UserList) SetUsers(val []User) {
	s.Users = val
}

// SetTotal sets the value of Total.
func (s *UserList) SetTotal(val int) {
	s.Total = val
}

// SetNextPageToken sets the value of NextPageToken.
func (s *UserList) SetNextPageToken(val OptString) {
	s.NextPageToken = val
}

func (*UserList) listUsersRes() {}

// User's wishlist of characters.
// Ref: #/components/schemas/Wishlist
type Wishlist struct {
	// List of characters in wishlist.
	Characters []Character `json:"characters"`
	// Total number of characters in the wishlist across all pages.
	Total int `json:"total"`
	// Token for retrieving the next page of results.
	NextPageToken OptString `json:"next_page_token"`
}

// GetCharacters returns the value of Characters.
func (s *Wishlist) GetCharacters() []Character {
	return s.Characters
}

// GetTotal returns the value of Total.
func (s *Wishlist) GetTotal() int {
	return s.Total
}

// GetNextPageToken returns the value of NextPageToken.
func (s *Wishlist) GetNextPageToken() OptString {
	return s.NextPageToken
}

// SetCharacters sets the value of Characters.
func (s *Wishlist) SetCharacters(val []Character) {
	s.Characters = val
}

// SetTotal sets the value of Total.
func (s *Wishlist) SetTotal(val int) {
	s.Total = val
}

// SetNextPageToken sets the value of NextPageToken.
func (s *Wishlist) SetNextPageToken(val OptString) {
	s.NextPageToken = val
}

func (*Wishlist) getUserWishlistRes() {}
