// Code generated by ogen, DO NOT EDIT.
package api

type FindUserLegacyRes interface {
	findUserLegacyRes()
}

type GetUserCollectionRes interface {
	getUserCollectionRes()
}

type GetUserFavoriteRes interface {
	getUserFavoriteRes()
}

type GetUserLegacyRes interface {
	getUserLegacyRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUserWishlistRes interface {
	getUserWishlistRes()
}

type ListUsersRes interface {
	listUsersRes()
}
