// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// FindUserParams is parameters of findUser operation.
type FindUserParams struct {
	// Anilist user URL (e.g., "https://anilist.co/user/animefan").
	Anilist OptString `json:",omitempty,omitzero"`
	// Discord username.
	Discord OptString `json:",omitempty,omitzero"`
}

func unpackFindUserParams(packed middleware.Parameters) (params FindUserParams) {
	{
		key := middleware.ParameterKey{
			Name: "anilist",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Anilist = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "discord",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Discord = v.(OptString)
		}
	}
	return params
}

func decodeFindUserParams(args [0]string, argsEscaped bool, r *http.Request) (params FindUserParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: anilist.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "anilist",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAnilistVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAnilistVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Anilist.SetTo(paramsDotAnilistVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "anilist",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: discord.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "discord",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDiscordVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscordVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Discord.SetTo(paramsDotDiscordVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discord",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// FindUserV1Params is parameters of findUserV1 operation.
type FindUserV1Params struct {
	// Anilist user URL (e.g., "https://anilist.co/user/animefan").
	Anilist OptString `json:",omitempty,omitzero"`
	// Discord username.
	Discord OptString `json:",omitempty,omitzero"`
}

func unpackFindUserV1Params(packed middleware.Parameters) (params FindUserV1Params) {
	{
		key := middleware.ParameterKey{
			Name: "anilist",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Anilist = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "discord",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Discord = v.(OptString)
		}
	}
	return params
}

func decodeFindUserV1Params(args [0]string, argsEscaped bool, r *http.Request) (params FindUserV1Params, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: anilist.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "anilist",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAnilistVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAnilistVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Anilist.SetTo(paramsDotAnilistVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "anilist",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: discord.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "discord",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDiscordVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotDiscordVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Discord.SetTo(paramsDotDiscordVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "discord",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserParams is parameters of getUser operation.
type GetUserParams struct {
	// User ID (can be passed as string or numeric).
	UserID string
}

func unpackGetUserParams(packed middleware.Parameters) (params GetUserParams) {
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(string)
	}
	return params
}

func decodeGetUserParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUserParams, _ error) {
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUserV1Params is parameters of getUserV1 operation.
type GetUserV1Params struct {
	// User ID (can be passed as string or numeric).
	UserID string
}

func unpackGetUserV1Params(packed middleware.Parameters) (params GetUserV1Params) {
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(string)
	}
	return params
}

func decodeGetUserV1Params(args [1]string, argsEscaped bool, r *http.Request) (params GetUserV1Params, _ error) {
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetWishlistParams is parameters of getWishlist operation.
type GetWishlistParams struct {
	// User ID (can be passed as string or numeric).
	UserID string
}

func unpackGetWishlistParams(packed middleware.Parameters) (params GetWishlistParams) {
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(string)
	}
	return params
}

func decodeGetWishlistParams(args [1]string, argsEscaped bool, r *http.Request) (params GetWishlistParams, _ error) {
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
