// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mocks/store_mock.go -package=mocks -mock_names=Store=MockStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	catalog "github.com/karitham/waifubot/catalog"
	collection "github.com/karitham/waifubot/collection"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddTokens mocks base method.
func (m *MockUserRepository) AddTokens(ctx context.Context, userID collection.UserID, amount int32) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTokens", ctx, userID, amount)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTokens indicates an expected call of AddTokens.
func (mr *MockUserRepositoryMockRecorder) AddTokens(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTokens", reflect.TypeOf((*MockUserRepository)(nil).AddTokens), ctx, userID, amount)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, userID collection.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, userID)
}

// GetUser mocks base method.
func (m *MockUserRepository) GetUser(ctx context.Context, userID collection.UserID) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepositoryMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), ctx, userID)
}

// GetUserByAnilist mocks base method.
func (m *MockUserRepository) GetUserByAnilist(ctx context.Context, anilistURL string) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAnilist", ctx, anilistURL)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAnilist indicates an expected call of GetUserByAnilist.
func (mr *MockUserRepositoryMockRecorder) GetUserByAnilist(ctx, anilistURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAnilist", reflect.TypeOf((*MockUserRepository)(nil).GetUserByAnilist), ctx, anilistURL)
}

// GetUserByDiscordUsername mocks base method.
func (m *MockUserRepository) GetUserByDiscordUsername(ctx context.Context, username string) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByDiscordUsername", ctx, username)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByDiscordUsername indicates an expected call of GetUserByDiscordUsername.
func (mr *MockUserRepositoryMockRecorder) GetUserByDiscordUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByDiscordUsername", reflect.TypeOf((*MockUserRepository)(nil).GetUserByDiscordUsername), ctx, username)
}

// SpendTokens mocks base method.
func (m *MockUserRepository) SpendTokens(ctx context.Context, userID collection.UserID, amount int32) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpendTokens", ctx, userID, amount)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpendTokens indicates an expected call of SpendTokens.
func (mr *MockUserRepositoryMockRecorder) SpendTokens(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpendTokens", reflect.TypeOf((*MockUserRepository)(nil).SpendTokens), ctx, userID, amount)
}

// UpdateAnilistURL mocks base method.
func (m *MockUserRepository) UpdateAnilistURL(ctx context.Context, userID collection.UserID, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnilistURL", ctx, userID, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnilistURL indicates an expected call of UpdateAnilistURL.
func (mr *MockUserRepositoryMockRecorder) UpdateAnilistURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnilistURL", reflect.TypeOf((*MockUserRepository)(nil).UpdateAnilistURL), ctx, userID, url)
}

// UpdateDiscordInfo mocks base method.
func (m *MockUserRepository) UpdateDiscordInfo(ctx context.Context, userID collection.UserID, username, avatar string, lastUpdated time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscordInfo", ctx, userID, username, avatar, lastUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiscordInfo indicates an expected call of UpdateDiscordInfo.
func (mr *MockUserRepositoryMockRecorder) UpdateDiscordInfo(ctx, userID, username, avatar, lastUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscordInfo", reflect.TypeOf((*MockUserRepository)(nil).UpdateDiscordInfo), ctx, userID, username, avatar, lastUpdated)
}

// UpdateFavorite mocks base method.
func (m *MockUserRepository) UpdateFavorite(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavorite", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFavorite indicates an expected call of UpdateFavorite.
func (mr *MockUserRepositoryMockRecorder) UpdateFavorite(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavorite", reflect.TypeOf((*MockUserRepository)(nil).UpdateFavorite), ctx, userID, charID)
}

// UpdateLastRoll mocks base method.
func (m *MockUserRepository) UpdateLastRoll(ctx context.Context, userID collection.UserID, when time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRoll", ctx, userID, when)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRoll indicates an expected call of UpdateLastRoll.
func (mr *MockUserRepositoryMockRecorder) UpdateLastRoll(ctx, userID, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRoll", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastRoll), ctx, userID, when)
}

// UpdateQuote mocks base method.
func (m *MockUserRepository) UpdateQuote(ctx context.Context, userID collection.UserID, quote string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuote", ctx, userID, quote)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuote indicates an expected call of UpdateQuote.
func (mr *MockUserRepositoryMockRecorder) UpdateQuote(ctx, userID, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuote", reflect.TypeOf((*MockUserRepository)(nil).UpdateQuote), ctx, userID, quote)
}

// MockCollectionRepository is a mock of CollectionRepository interface.
type MockCollectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionRepositoryMockRecorder
	isgomock struct{}
}

// MockCollectionRepositoryMockRecorder is the mock recorder for MockCollectionRepository.
type MockCollectionRepositoryMockRecorder struct {
	mock *MockCollectionRepository
}

// NewMockCollectionRepository creates a new mock instance.
func NewMockCollectionRepository(ctrl *gomock.Controller) *MockCollectionRepository {
	mock := &MockCollectionRepository{ctrl: ctrl}
	mock.recorder = &MockCollectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionRepository) EXPECT() *MockCollectionRepositoryMockRecorder {
	return m.recorder
}

// AddToCollection mocks base method.
func (m *MockCollectionRepository) AddToCollection(ctx context.Context, userID collection.UserID, char collection.Character, source string, acquiredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCollection", ctx, userID, char, source, acquiredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToCollection indicates an expected call of AddToCollection.
func (mr *MockCollectionRepositoryMockRecorder) AddToCollection(ctx, userID, char, source, acquiredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCollection", reflect.TypeOf((*MockCollectionRepository)(nil).AddToCollection), ctx, userID, char, source, acquiredAt)
}

// CharacterOwnedByUser mocks base method.
func (m *MockCollectionRepository) CharacterOwnedByUser(ctx context.Context, userID collection.UserID, charID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CharacterOwnedByUser", ctx, userID, charID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CharacterOwnedByUser indicates an expected call of CharacterOwnedByUser.
func (mr *MockCollectionRepositoryMockRecorder) CharacterOwnedByUser(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CharacterOwnedByUser", reflect.TypeOf((*MockCollectionRepository)(nil).CharacterOwnedByUser), ctx, userID, charID)
}

// CountCollection mocks base method.
func (m *MockCollectionRepository) CountCollection(ctx context.Context, userID collection.UserID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollection", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCollection indicates an expected call of CountCollection.
func (mr *MockCollectionRepositoryMockRecorder) CountCollection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollection", reflect.TypeOf((*MockCollectionRepository)(nil).CountCollection), ctx, userID)
}

// GetCollection mocks base method.
func (m *MockCollectionRepository) GetCollection(ctx context.Context, userID collection.UserID) ([]collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx, userID)
	ret0, _ := ret[0].([]collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCollectionRepositoryMockRecorder) GetCollection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCollectionRepository)(nil).GetCollection), ctx, userID)
}

// GetCollectionIDs mocks base method.
func (m *MockCollectionRepository) GetCollectionIDs(ctx context.Context, userID collection.UserID) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionIDs", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionIDs indicates an expected call of GetCollectionIDs.
func (mr *MockCollectionRepositoryMockRecorder) GetCollectionIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionIDs", reflect.TypeOf((*MockCollectionRepository)(nil).GetCollectionIDs), ctx, userID)
}

// GetOwnedCharacter mocks base method.
func (m *MockCollectionRepository) GetOwnedCharacter(ctx context.Context, userID collection.UserID, charID int64) (collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnedCharacter", ctx, userID, charID)
	ret0, _ := ret[0].(collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedCharacter indicates an expected call of GetOwnedCharacter.
func (mr *MockCollectionRepositoryMockRecorder) GetOwnedCharacter(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedCharacter", reflect.TypeOf((*MockCollectionRepository)(nil).GetOwnedCharacter), ctx, userID, charID)
}

// GiveCharacter mocks base method.
func (m *MockCollectionRepository) GiveCharacter(ctx context.Context, from, to collection.UserID, charID int64) (collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GiveCharacter", ctx, from, to, charID)
	ret0, _ := ret[0].(collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GiveCharacter indicates an expected call of GiveCharacter.
func (mr *MockCollectionRepositoryMockRecorder) GiveCharacter(ctx, from, to, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveCharacter", reflect.TypeOf((*MockCollectionRepository)(nil).GiveCharacter), ctx, from, to, charID)
}

// RemoveFromCollection mocks base method.
func (m *MockCollectionRepository) RemoveFromCollection(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromCollection", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromCollection indicates an expected call of RemoveFromCollection.
func (mr *MockCollectionRepositoryMockRecorder) RemoveFromCollection(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromCollection", reflect.TypeOf((*MockCollectionRepository)(nil).RemoveFromCollection), ctx, userID, charID)
}

// RemoveFromWishlist mocks base method.
func (m *MockCollectionRepository) RemoveFromWishlist(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromWishlist", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromWishlist indicates an expected call of RemoveFromWishlist.
func (mr *MockCollectionRepositoryMockRecorder) RemoveFromWishlist(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromWishlist", reflect.TypeOf((*MockCollectionRepository)(nil).RemoveFromWishlist), ctx, userID, charID)
}

// MockDropRepository is a mock of DropRepository interface.
type MockDropRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDropRepositoryMockRecorder
	isgomock struct{}
}

// MockDropRepositoryMockRecorder is the mock recorder for MockDropRepository.
type MockDropRepositoryMockRecorder struct {
	mock *MockDropRepository
}

// NewMockDropRepository creates a new mock instance.
func NewMockDropRepository(ctrl *gomock.Controller) *MockDropRepository {
	mock := &MockDropRepository{ctrl: ctrl}
	mock.recorder = &MockDropRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDropRepository) EXPECT() *MockDropRepositoryMockRecorder {
	return m.recorder
}

// DeleteDrop mocks base method.
func (m *MockDropRepository) DeleteDrop(ctx context.Context, channelID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrop", ctx, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrop indicates an expected call of DeleteDrop.
func (mr *MockDropRepositoryMockRecorder) DeleteDrop(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrop", reflect.TypeOf((*MockDropRepository)(nil).DeleteDrop), ctx, channelID)
}

// GetDropForUpdate mocks base method.
func (m *MockDropRepository) GetDropForUpdate(ctx context.Context, channelID uint64) (collection.Drop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDropForUpdate", ctx, channelID)
	ret0, _ := ret[0].(collection.Drop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDropForUpdate indicates an expected call of GetDropForUpdate.
func (mr *MockDropRepositoryMockRecorder) GetDropForUpdate(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDropForUpdate", reflect.TypeOf((*MockDropRepository)(nil).GetDropForUpdate), ctx, channelID)
}

// MockGuildQuerier is a mock of GuildQuerier interface.
type MockGuildQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockGuildQuerierMockRecorder
	isgomock struct{}
}

// MockGuildQuerierMockRecorder is the mock recorder for MockGuildQuerier.
type MockGuildQuerierMockRecorder struct {
	mock *MockGuildQuerier
}

// NewMockGuildQuerier creates a new mock instance.
func NewMockGuildQuerier(ctrl *gomock.Controller) *MockGuildQuerier {
	mock := &MockGuildQuerier{ctrl: ctrl}
	mock.recorder = &MockGuildQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuildQuerier) EXPECT() *MockGuildQuerierMockRecorder {
	return m.recorder
}

// CompleteIndexingJob mocks base method.
func (m *MockGuildQuerier) CompleteIndexingJob(ctx context.Context, guildID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIndexingJob", ctx, guildID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteIndexingJob indicates an expected call of CompleteIndexingJob.
func (mr *MockGuildQuerierMockRecorder) CompleteIndexingJob(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteIndexingJob", reflect.TypeOf((*MockGuildQuerier)(nil).CompleteIndexingJob), ctx, guildID)
}

// DeleteGuildMembersNotIn mocks base method.
func (m *MockGuildQuerier) DeleteGuildMembersNotIn(ctx context.Context, guildID uint64, memberIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGuildMembersNotIn", ctx, guildID, memberIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGuildMembersNotIn indicates an expected call of DeleteGuildMembersNotIn.
func (mr *MockGuildQuerierMockRecorder) DeleteGuildMembersNotIn(ctx, guildID, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGuildMembersNotIn", reflect.TypeOf((*MockGuildQuerier)(nil).DeleteGuildMembersNotIn), ctx, guildID, memberIDs)
}

// IsGuildIndexed mocks base method.
func (m *MockGuildQuerier) IsGuildIndexed(ctx context.Context, guildID uint64) (collection.GuildIndexStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGuildIndexed", ctx, guildID)
	ret0, _ := ret[0].(collection.GuildIndexStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsGuildIndexed indicates an expected call of IsGuildIndexed.
func (mr *MockGuildQuerierMockRecorder) IsGuildIndexed(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGuildIndexed", reflect.TypeOf((*MockGuildQuerier)(nil).IsGuildIndexed), ctx, guildID)
}

// StartIndexingJob mocks base method.
func (m *MockGuildQuerier) StartIndexingJob(ctx context.Context, guildID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartIndexingJob", ctx, guildID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartIndexingJob indicates an expected call of StartIndexingJob.
func (mr *MockGuildQuerierMockRecorder) StartIndexingJob(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartIndexingJob", reflect.TypeOf((*MockGuildQuerier)(nil).StartIndexingJob), ctx, guildID)
}

// UpsertGuildMembers mocks base method.
func (m *MockGuildQuerier) UpsertGuildMembers(ctx context.Context, guildID uint64, memberIDs []uint64, indexedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGuildMembers", ctx, guildID, memberIDs, indexedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGuildMembers indicates an expected call of UpsertGuildMembers.
func (mr *MockGuildQuerierMockRecorder) UpsertGuildMembers(ctx, guildID, memberIDs, indexedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGuildMembers", reflect.TypeOf((*MockGuildQuerier)(nil).UpsertGuildMembers), ctx, guildID, memberIDs, indexedAt)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddToCollection mocks base method.
func (m *MockStore) AddToCollection(ctx context.Context, userID collection.UserID, char collection.Character, source string, acquiredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCollection", ctx, userID, char, source, acquiredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToCollection indicates an expected call of AddToCollection.
func (mr *MockStoreMockRecorder) AddToCollection(ctx, userID, char, source, acquiredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCollection", reflect.TypeOf((*MockStore)(nil).AddToCollection), ctx, userID, char, source, acquiredAt)
}

// AddTokens mocks base method.
func (m *MockStore) AddTokens(ctx context.Context, userID collection.UserID, amount int32) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTokens", ctx, userID, amount)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTokens indicates an expected call of AddTokens.
func (mr *MockStoreMockRecorder) AddTokens(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTokens", reflect.TypeOf((*MockStore)(nil).AddTokens), ctx, userID, amount)
}

// CharacterOwnedByUser mocks base method.
func (m *MockStore) CharacterOwnedByUser(ctx context.Context, userID collection.UserID, charID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CharacterOwnedByUser", ctx, userID, charID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CharacterOwnedByUser indicates an expected call of CharacterOwnedByUser.
func (mr *MockStoreMockRecorder) CharacterOwnedByUser(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CharacterOwnedByUser", reflect.TypeOf((*MockStore)(nil).CharacterOwnedByUser), ctx, userID, charID)
}

// Commit mocks base method.
func (m *MockStore) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockStoreMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockStore)(nil).Commit), ctx)
}

// CompleteIndexingJob mocks base method.
func (m *MockStore) CompleteIndexingJob(ctx context.Context, guildID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIndexingJob", ctx, guildID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteIndexingJob indicates an expected call of CompleteIndexingJob.
func (mr *MockStoreMockRecorder) CompleteIndexingJob(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteIndexingJob", reflect.TypeOf((*MockStore)(nil).CompleteIndexingJob), ctx, guildID)
}

// CountCollection mocks base method.
func (m *MockStore) CountCollection(ctx context.Context, userID collection.UserID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollection", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCollection indicates an expected call of CountCollection.
func (mr *MockStoreMockRecorder) CountCollection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollection", reflect.TypeOf((*MockStore)(nil).CountCollection), ctx, userID)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, userID collection.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, userID)
}

// DeleteDrop mocks base method.
func (m *MockStore) DeleteDrop(ctx context.Context, channelID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrop", ctx, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrop indicates an expected call of DeleteDrop.
func (mr *MockStoreMockRecorder) DeleteDrop(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrop", reflect.TypeOf((*MockStore)(nil).DeleteDrop), ctx, channelID)
}

// DeleteGuildMembersNotIn mocks base method.
func (m *MockStore) DeleteGuildMembersNotIn(ctx context.Context, guildID uint64, memberIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGuildMembersNotIn", ctx, guildID, memberIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGuildMembersNotIn indicates an expected call of DeleteGuildMembersNotIn.
func (mr *MockStoreMockRecorder) DeleteGuildMembersNotIn(ctx, guildID, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGuildMembersNotIn", reflect.TypeOf((*MockStore)(nil).DeleteGuildMembersNotIn), ctx, guildID, memberIDs)
}

// GetCharacterByID mocks base method.
func (m *MockStore) GetCharacterByID(ctx context.Context, charID int64) (catalog.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterByID", ctx, charID)
	ret0, _ := ret[0].(catalog.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterByID indicates an expected call of GetCharacterByID.
func (mr *MockStoreMockRecorder) GetCharacterByID(ctx, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterByID", reflect.TypeOf((*MockStore)(nil).GetCharacterByID), ctx, charID)
}

// GetCharacterHoldersInGuild mocks base method.
func (m *MockStore) GetCharacterHoldersInGuild(ctx context.Context, guildID uint64, charID int64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacterHoldersInGuild", ctx, guildID, charID)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacterHoldersInGuild indicates an expected call of GetCharacterHoldersInGuild.
func (mr *MockStoreMockRecorder) GetCharacterHoldersInGuild(ctx, guildID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacterHoldersInGuild", reflect.TypeOf((*MockStore)(nil).GetCharacterHoldersInGuild), ctx, guildID, charID)
}

// GetCollection mocks base method.
func (m *MockStore) GetCollection(ctx context.Context, userID collection.UserID) ([]collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx, userID)
	ret0, _ := ret[0].([]collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockStoreMockRecorder) GetCollection(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockStore)(nil).GetCollection), ctx, userID)
}

// GetCollectionIDs mocks base method.
func (m *MockStore) GetCollectionIDs(ctx context.Context, userID collection.UserID) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionIDs", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionIDs indicates an expected call of GetCollectionIDs.
func (mr *MockStoreMockRecorder) GetCollectionIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionIDs", reflect.TypeOf((*MockStore)(nil).GetCollectionIDs), ctx, userID)
}

// GetDropForUpdate mocks base method.
func (m *MockStore) GetDropForUpdate(ctx context.Context, channelID uint64) (collection.Drop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDropForUpdate", ctx, channelID)
	ret0, _ := ret[0].(collection.Drop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDropForUpdate indicates an expected call of GetDropForUpdate.
func (mr *MockStoreMockRecorder) GetDropForUpdate(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDropForUpdate", reflect.TypeOf((*MockStore)(nil).GetDropForUpdate), ctx, channelID)
}

// GetOwnedCharacter mocks base method.
func (m *MockStore) GetOwnedCharacter(ctx context.Context, userID collection.UserID, charID int64) (collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnedCharacter", ctx, userID, charID)
	ret0, _ := ret[0].(collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedCharacter indicates an expected call of GetOwnedCharacter.
func (mr *MockStoreMockRecorder) GetOwnedCharacter(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedCharacter", reflect.TypeOf((*MockStore)(nil).GetOwnedCharacter), ctx, userID, charID)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, userID collection.UserID) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, userID)
}

// GetUserByAnilist mocks base method.
func (m *MockStore) GetUserByAnilist(ctx context.Context, anilistURL string) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAnilist", ctx, anilistURL)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAnilist indicates an expected call of GetUserByAnilist.
func (mr *MockStoreMockRecorder) GetUserByAnilist(ctx, anilistURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAnilist", reflect.TypeOf((*MockStore)(nil).GetUserByAnilist), ctx, anilistURL)
}

// GetUserByDiscordUsername mocks base method.
func (m *MockStore) GetUserByDiscordUsername(ctx context.Context, username string) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByDiscordUsername", ctx, username)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByDiscordUsername indicates an expected call of GetUserByDiscordUsername.
func (mr *MockStoreMockRecorder) GetUserByDiscordUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByDiscordUsername", reflect.TypeOf((*MockStore)(nil).GetUserByDiscordUsername), ctx, username)
}

// GiveCharacter mocks base method.
func (m *MockStore) GiveCharacter(ctx context.Context, from, to collection.UserID, charID int64) (collection.OwnedCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GiveCharacter", ctx, from, to, charID)
	ret0, _ := ret[0].(collection.OwnedCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GiveCharacter indicates an expected call of GiveCharacter.
func (mr *MockStoreMockRecorder) GiveCharacter(ctx, from, to, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveCharacter", reflect.TypeOf((*MockStore)(nil).GiveCharacter), ctx, from, to, charID)
}

// IsGuildIndexed mocks base method.
func (m *MockStore) IsGuildIndexed(ctx context.Context, guildID uint64) (collection.GuildIndexStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGuildIndexed", ctx, guildID)
	ret0, _ := ret[0].(collection.GuildIndexStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsGuildIndexed indicates an expected call of IsGuildIndexed.
func (mr *MockStoreMockRecorder) IsGuildIndexed(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGuildIndexed", reflect.TypeOf((*MockStore)(nil).IsGuildIndexed), ctx, guildID)
}

// RemoveFromCollection mocks base method.
func (m *MockStore) RemoveFromCollection(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromCollection", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromCollection indicates an expected call of RemoveFromCollection.
func (mr *MockStoreMockRecorder) RemoveFromCollection(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromCollection", reflect.TypeOf((*MockStore)(nil).RemoveFromCollection), ctx, userID, charID)
}

// RemoveFromWishlist mocks base method.
func (m *MockStore) RemoveFromWishlist(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromWishlist", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromWishlist indicates an expected call of RemoveFromWishlist.
func (mr *MockStoreMockRecorder) RemoveFromWishlist(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromWishlist", reflect.TypeOf((*MockStore)(nil).RemoveFromWishlist), ctx, userID, charID)
}

// Rollback mocks base method.
func (m *MockStore) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockStoreMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockStore)(nil).Rollback), ctx)
}

// SearchCharacters mocks base method.
func (m *MockStore) SearchCharacters(ctx context.Context, userID uint64, term string) ([]catalog.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCharacters", ctx, userID, term)
	ret0, _ := ret[0].([]catalog.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCharacters indicates an expected call of SearchCharacters.
func (mr *MockStoreMockRecorder) SearchCharacters(ctx, userID, term any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCharacters", reflect.TypeOf((*MockStore)(nil).SearchCharacters), ctx, userID, term)
}

// SearchGlobalCharacters mocks base method.
func (m *MockStore) SearchGlobalCharacters(ctx context.Context, term string) ([]catalog.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGlobalCharacters", ctx, term)
	ret0, _ := ret[0].([]catalog.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGlobalCharacters indicates an expected call of SearchGlobalCharacters.
func (mr *MockStoreMockRecorder) SearchGlobalCharacters(ctx, term any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGlobalCharacters", reflect.TypeOf((*MockStore)(nil).SearchGlobalCharacters), ctx, term)
}

// SpendTokens mocks base method.
func (m *MockStore) SpendTokens(ctx context.Context, userID collection.UserID, amount int32) (collection.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpendTokens", ctx, userID, amount)
	ret0, _ := ret[0].(collection.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpendTokens indicates an expected call of SpendTokens.
func (mr *MockStoreMockRecorder) SpendTokens(ctx, userID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpendTokens", reflect.TypeOf((*MockStore)(nil).SpendTokens), ctx, userID, amount)
}

// StartIndexingJob mocks base method.
func (m *MockStore) StartIndexingJob(ctx context.Context, guildID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartIndexingJob", ctx, guildID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartIndexingJob indicates an expected call of StartIndexingJob.
func (mr *MockStoreMockRecorder) StartIndexingJob(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartIndexingJob", reflect.TypeOf((*MockStore)(nil).StartIndexingJob), ctx, guildID)
}

// UpdateAnilistURL mocks base method.
func (m *MockStore) UpdateAnilistURL(ctx context.Context, userID collection.UserID, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnilistURL", ctx, userID, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnilistURL indicates an expected call of UpdateAnilistURL.
func (mr *MockStoreMockRecorder) UpdateAnilistURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnilistURL", reflect.TypeOf((*MockStore)(nil).UpdateAnilistURL), ctx, userID, url)
}

// UpdateDiscordInfo mocks base method.
func (m *MockStore) UpdateDiscordInfo(ctx context.Context, userID collection.UserID, username, avatar string, lastUpdated time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscordInfo", ctx, userID, username, avatar, lastUpdated)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDiscordInfo indicates an expected call of UpdateDiscordInfo.
func (mr *MockStoreMockRecorder) UpdateDiscordInfo(ctx, userID, username, avatar, lastUpdated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscordInfo", reflect.TypeOf((*MockStore)(nil).UpdateDiscordInfo), ctx, userID, username, avatar, lastUpdated)
}

// UpdateFavorite mocks base method.
func (m *MockStore) UpdateFavorite(ctx context.Context, userID collection.UserID, charID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavorite", ctx, userID, charID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFavorite indicates an expected call of UpdateFavorite.
func (mr *MockStoreMockRecorder) UpdateFavorite(ctx, userID, charID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavorite", reflect.TypeOf((*MockStore)(nil).UpdateFavorite), ctx, userID, charID)
}

// UpdateLastRoll mocks base method.
func (m *MockStore) UpdateLastRoll(ctx context.Context, userID collection.UserID, when time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastRoll", ctx, userID, when)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastRoll indicates an expected call of UpdateLastRoll.
func (mr *MockStoreMockRecorder) UpdateLastRoll(ctx, userID, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastRoll", reflect.TypeOf((*MockStore)(nil).UpdateLastRoll), ctx, userID, when)
}

// UpdateQuote mocks base method.
func (m *MockStore) UpdateQuote(ctx context.Context, userID collection.UserID, quote string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuote", ctx, userID, quote)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuote indicates an expected call of UpdateQuote.
func (mr *MockStoreMockRecorder) UpdateQuote(ctx, userID, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuote", reflect.TypeOf((*MockStore)(nil).UpdateQuote), ctx, userID, quote)
}

// UpsertCharacter mocks base method.
func (m *MockStore) UpsertCharacter(ctx context.Context, char catalog.Character) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCharacter", ctx, char)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCharacter indicates an expected call of UpsertCharacter.
func (mr *MockStoreMockRecorder) UpsertCharacter(ctx, char any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCharacter", reflect.TypeOf((*MockStore)(nil).UpsertCharacter), ctx, char)
}

// UpsertGuildMembers mocks base method.
func (m *MockStore) UpsertGuildMembers(ctx context.Context, guildID uint64, memberIDs []uint64, indexedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertGuildMembers", ctx, guildID, memberIDs, indexedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertGuildMembers indicates an expected call of UpsertGuildMembers.
func (mr *MockStoreMockRecorder) UpsertGuildMembers(ctx, guildID, memberIDs, indexedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertGuildMembers", reflect.TypeOf((*MockStore)(nil).UpsertGuildMembers), ctx, guildID, memberIDs, indexedAt)
}

// WithTx mocks base method.
func (m *MockStore) WithTx(ctx context.Context) (collection.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx)
	ret0, _ := ret[0].(collection.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithTx indicates an expected call of WithTx.
func (mr *MockStoreMockRecorder) WithTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockStore)(nil).WithTx), ctx)
}
