// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package commandstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommandMigration struct {
	Hash       string
	DeployedAt pgtype.Timestamp
}
