// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package commandstore

import (
	"context"
)

type Querier interface {
	GetCommandHash(ctx context.Context) (string, error)
	SetCommandHash(ctx context.Context, hash string) error
	UpdateCommandHash(ctx context.Context, hash string) error
}

var _ Querier = (*Queries)(nil)
