// Code generated by MockGen. DO NOT EDIT.
// Source: ../storage/collectionstore/querier.go
//
// Generated by this command:
//
//	mockgen -source=../storage/collectionstore/querier.go -destination=collectionstore_mock.go -package=collection -mock_names=Querier=MockCollectionQuerier
//

// Package collection is a generated GoMock package.
package collection

import (
	context "context"
	reflect "reflect"

	collectionstore "github.com/karitham/waifubot/storage/collectionstore"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionQuerier is a mock of Querier interface.
type MockCollectionQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionQuerierMockRecorder
	isgomock struct{}
}

// MockCollectionQuerierMockRecorder is the mock recorder for MockCollectionQuerier.
type MockCollectionQuerierMockRecorder struct {
	mock *MockCollectionQuerier
}

// NewMockCollectionQuerier creates a new mock instance.
func NewMockCollectionQuerier(ctrl *gomock.Controller) *MockCollectionQuerier {
	mock := &MockCollectionQuerier{ctrl: ctrl}
	mock.recorder = &MockCollectionQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionQuerier) EXPECT() *MockCollectionQuerierMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockCollectionQuerier) Count(ctx context.Context, userID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockCollectionQuerierMockRecorder) Count(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCollectionQuerier)(nil).Count), ctx, userID)
}

// Delete mocks base method.
func (m *MockCollectionQuerier) Delete(ctx context.Context, arg collectionstore.DeleteParams) (collectionstore.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, arg)
	ret0, _ := ret[0].(collectionstore.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionQuerierMockRecorder) Delete(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionQuerier)(nil).Delete), ctx, arg)
}

// Get mocks base method.
func (m *MockCollectionQuerier) Get(ctx context.Context, arg collectionstore.GetParams) (collectionstore.GetRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, arg)
	ret0, _ := ret[0].(collectionstore.GetRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCollectionQuerierMockRecorder) Get(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCollectionQuerier)(nil).Get), ctx, arg)
}

// GetByID mocks base method.
func (m *MockCollectionQuerier) GetByID(ctx context.Context, id int64) (collectionstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(collectionstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCollectionQuerierMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCollectionQuerier)(nil).GetByID), ctx, id)
}

// Give mocks base method.
func (m *MockCollectionQuerier) Give(ctx context.Context, arg collectionstore.GiveParams) (collectionstore.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Give", ctx, arg)
	ret0, _ := ret[0].(collectionstore.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Give indicates an expected call of Give.
func (mr *MockCollectionQuerierMockRecorder) Give(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Give", reflect.TypeOf((*MockCollectionQuerier)(nil).Give), ctx, arg)
}

// Insert mocks base method.
func (m *MockCollectionQuerier) Insert(ctx context.Context, arg collectionstore.InsertParams) (collectionstore.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, arg)
	ret0, _ := ret[0].(collectionstore.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockCollectionQuerierMockRecorder) Insert(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCollectionQuerier)(nil).Insert), ctx, arg)
}

// List mocks base method.
func (m *MockCollectionQuerier) List(ctx context.Context, userID uint64) ([]collectionstore.ListRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]collectionstore.ListRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCollectionQuerierMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCollectionQuerier)(nil).List), ctx, userID)
}

// ListIDs mocks base method.
func (m *MockCollectionQuerier) ListIDs(ctx context.Context, userID uint64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIDs", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIDs indicates an expected call of ListIDs.
func (mr *MockCollectionQuerierMockRecorder) ListIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIDs", reflect.TypeOf((*MockCollectionQuerier)(nil).ListIDs), ctx, userID)
}

// SearchCharacters mocks base method.
func (m *MockCollectionQuerier) SearchCharacters(ctx context.Context, arg collectionstore.SearchCharactersParams) ([]collectionstore.SearchCharactersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCharacters", ctx, arg)
	ret0, _ := ret[0].([]collectionstore.SearchCharactersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchCharacters indicates an expected call of SearchCharacters.
func (mr *MockCollectionQuerierMockRecorder) SearchCharacters(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCharacters", reflect.TypeOf((*MockCollectionQuerier)(nil).SearchCharacters), ctx, arg)
}

// SearchGlobalCharacters mocks base method.
func (m *MockCollectionQuerier) SearchGlobalCharacters(ctx context.Context, arg collectionstore.SearchGlobalCharactersParams) ([]collectionstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGlobalCharacters", ctx, arg)
	ret0, _ := ret[0].([]collectionstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGlobalCharacters indicates an expected call of SearchGlobalCharacters.
func (mr *MockCollectionQuerierMockRecorder) SearchGlobalCharacters(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGlobalCharacters", reflect.TypeOf((*MockCollectionQuerier)(nil).SearchGlobalCharacters), ctx, arg)
}

// UpdateImageName mocks base method.
func (m *MockCollectionQuerier) UpdateImageName(ctx context.Context, arg collectionstore.UpdateImageNameParams) (collectionstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImageName", ctx, arg)
	ret0, _ := ret[0].(collectionstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateImageName indicates an expected call of UpdateImageName.
func (mr *MockCollectionQuerierMockRecorder) UpdateImageName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImageName", reflect.TypeOf((*MockCollectionQuerier)(nil).UpdateImageName), ctx, arg)
}

// UpsertCharacter mocks base method.
func (m *MockCollectionQuerier) UpsertCharacter(ctx context.Context, arg collectionstore.UpsertCharacterParams) (collectionstore.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCharacter", ctx, arg)
	ret0, _ := ret[0].(collectionstore.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCharacter indicates an expected call of UpsertCharacter.
func (mr *MockCollectionQuerierMockRecorder) UpsertCharacter(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCharacter", reflect.TypeOf((*MockCollectionQuerier)(nil).UpsertCharacter), ctx, arg)
}

// UsersOwningCharFiltered mocks base method.
func (m *MockCollectionQuerier) UsersOwningCharFiltered(ctx context.Context, arg collectionstore.UsersOwningCharFilteredParams) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersOwningCharFiltered", ctx, arg)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersOwningCharFiltered indicates an expected call of UsersOwningCharFiltered.
func (mr *MockCollectionQuerierMockRecorder) UsersOwningCharFiltered(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersOwningCharFiltered", reflect.TypeOf((*MockCollectionQuerier)(nil).UsersOwningCharFiltered), ctx, arg)
}
