// Code generated by MockGen. DO NOT EDIT.
// Source: profile.go
//
// Generated by this command:
//
//	mockgen -source=profile.go -destination=profile_mock.go -package=collection -mock_names=Store=MockProfileStore,AnimeService=MockAnimeService
//

// Package collection is a generated GoMock package.
package collection

import (
	context "context"
	reflect "reflect"

	storage "github.com/karitham/waifubot/storage"
	collectionstore "github.com/karitham/waifubot/storage/collectionstore"
	commandstore "github.com/karitham/waifubot/storage/commandstore"
	guildstore "github.com/karitham/waifubot/storage/guildstore"
	userstore "github.com/karitham/waifubot/storage/userstore"
	wishliststore "github.com/karitham/waifubot/storage/wishliststore"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileStore is a mock of Store interface.
type MockProfileStore struct {
	ctrl     *gomock.Controller
	recorder *MockProfileStoreMockRecorder
	isgomock struct{}
}

// MockProfileStoreMockRecorder is the mock recorder for MockProfileStore.
type MockProfileStoreMockRecorder struct {
	mock *MockProfileStore
}

// NewMockProfileStore creates a new mock instance.
func NewMockProfileStore(ctrl *gomock.Controller) *MockProfileStore {
	mock := &MockProfileStore{ctrl: ctrl}
	mock.recorder = &MockProfileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileStore) EXPECT() *MockProfileStoreMockRecorder {
	return m.recorder
}

// CollectionStore mocks base method.
func (m *MockProfileStore) CollectionStore() collectionstore.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionStore")
	ret0, _ := ret[0].(collectionstore.Querier)
	return ret0
}

// CollectionStore indicates an expected call of CollectionStore.
func (mr *MockProfileStoreMockRecorder) CollectionStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionStore", reflect.TypeOf((*MockProfileStore)(nil).CollectionStore))
}

// CommandStore mocks base method.
func (m *MockProfileStore) CommandStore() commandstore.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandStore")
	ret0, _ := ret[0].(commandstore.Querier)
	return ret0
}

// CommandStore indicates an expected call of CommandStore.
func (mr *MockProfileStoreMockRecorder) CommandStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandStore", reflect.TypeOf((*MockProfileStore)(nil).CommandStore))
}

// Commit mocks base method.
func (m *MockProfileStore) Commit(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockProfileStoreMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockProfileStore)(nil).Commit), ctx)
}

// GuildStore mocks base method.
func (m *MockProfileStore) GuildStore() guildstore.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GuildStore")
	ret0, _ := ret[0].(guildstore.Querier)
	return ret0
}

// GuildStore indicates an expected call of GuildStore.
func (mr *MockProfileStoreMockRecorder) GuildStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GuildStore", reflect.TypeOf((*MockProfileStore)(nil).GuildStore))
}

// Rollback mocks base method.
func (m *MockProfileStore) Rollback(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockProfileStoreMockRecorder) Rollback(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockProfileStore)(nil).Rollback), ctx)
}

// Tx mocks base method.
func (m *MockProfileStore) Tx(ctx context.Context) (storage.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tx", ctx)
	ret0, _ := ret[0].(storage.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tx indicates an expected call of Tx.
func (mr *MockProfileStoreMockRecorder) Tx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tx", reflect.TypeOf((*MockProfileStore)(nil).Tx), ctx)
}

// UserStore mocks base method.
func (m *MockProfileStore) UserStore() userstore.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserStore")
	ret0, _ := ret[0].(userstore.Querier)
	return ret0
}

// UserStore indicates an expected call of UserStore.
func (mr *MockProfileStoreMockRecorder) UserStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserStore", reflect.TypeOf((*MockProfileStore)(nil).UserStore))
}

// WishlistStore mocks base method.
func (m *MockProfileStore) WishlistStore() wishliststore.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WishlistStore")
	ret0, _ := ret[0].(wishliststore.Querier)
	return ret0
}

// WishlistStore indicates an expected call of WishlistStore.
func (mr *MockProfileStoreMockRecorder) WishlistStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WishlistStore", reflect.TypeOf((*MockProfileStore)(nil).WishlistStore))
}

// MockAnimeService is a mock of AnimeService interface.
type MockAnimeService struct {
	ctrl     *gomock.Controller
	recorder *MockAnimeServiceMockRecorder
	isgomock struct{}
}

// MockAnimeServiceMockRecorder is the mock recorder for MockAnimeService.
type MockAnimeServiceMockRecorder struct {
	mock *MockAnimeService
}

// NewMockAnimeService creates a new mock instance.
func NewMockAnimeService(ctrl *gomock.Controller) *MockAnimeService {
	mock := &MockAnimeService{ctrl: ctrl}
	mock.recorder = &MockAnimeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnimeService) EXPECT() *MockAnimeServiceMockRecorder {
	return m.recorder
}

// Anime mocks base method.
func (m *MockAnimeService) Anime(ctx context.Context, name string) ([]Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Anime", ctx, name)
	ret0, _ := ret[0].([]Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Anime indicates an expected call of Anime.
func (mr *MockAnimeServiceMockRecorder) Anime(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Anime", reflect.TypeOf((*MockAnimeService)(nil).Anime), ctx, name)
}

// Character mocks base method.
func (m *MockAnimeService) Character(ctx context.Context, name string) ([]MediaCharacter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Character", ctx, name)
	ret0, _ := ret[0].([]MediaCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Character indicates an expected call of Character.
func (mr *MockAnimeServiceMockRecorder) Character(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Character", reflect.TypeOf((*MockAnimeService)(nil).Character), ctx, name)
}

// Manga mocks base method.
func (m *MockAnimeService) Manga(ctx context.Context, name string) ([]Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manga", ctx, name)
	ret0, _ := ret[0].([]Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manga indicates an expected call of Manga.
func (mr *MockAnimeServiceMockRecorder) Manga(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manga", reflect.TypeOf((*MockAnimeService)(nil).Manga), ctx, name)
}

// RandomChar mocks base method.
func (m *MockAnimeService) RandomChar(ctx context.Context, notIn ...int64) (MediaCharacter, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range notIn {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RandomChar", varargs...)
	ret0, _ := ret[0].(MediaCharacter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RandomChar indicates an expected call of RandomChar.
func (mr *MockAnimeServiceMockRecorder) RandomChar(ctx any, notIn ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, notIn...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RandomChar", reflect.TypeOf((*MockAnimeService)(nil).RandomChar), varargs...)
}

// User mocks base method.
func (m *MockAnimeService) User(ctx context.Context, name string) ([]TrackerUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, name)
	ret0, _ := ret[0].([]TrackerUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockAnimeServiceMockRecorder) User(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockAnimeService)(nil).User), ctx, name)
}
