// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dropstore

type ChannelDrop struct {
	ChannelID   uint64
	CharacterID int64
}

type Character struct {
	ID         int64
	Name       string
	Image      string
	MediaTitle string
}
