// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package collectionstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID    int64
	Name  string
	Image string
}

type Collection struct {
	UserID      uint64
	CharacterID int64
	Source      string
	AcquiredAt  pgtype.Timestamp
}
