// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package collectionstore

import (
	"context"
)

type Querier interface {
	Count(ctx context.Context, userID uint64) (int64, error)
	Delete(ctx context.Context, arg DeleteParams) (Character, error)
	Get(ctx context.Context, arg GetParams) (Character, error)
	GetByID(ctx context.Context, id int64) (Character, error)
	Give(ctx context.Context, arg GiveParams) (Character, error)
	Insert(ctx context.Context, arg InsertParams) error
	List(ctx context.Context, userID uint64) ([]Character, error)
	ListIDs(ctx context.Context, userID uint64) ([]int64, error)
	SearchCharacters(ctx context.Context, arg SearchCharactersParams) ([]Character, error)
	SearchGlobalCharacters(ctx context.Context, arg SearchGlobalCharactersParams) ([]SearchGlobalCharactersRow, error)
	UpdateImageName(ctx context.Context, arg UpdateImageNameParams) (Character, error)
	UsersOwningCharFiltered(ctx context.Context, arg UsersOwningCharFilteredParams) ([]uint64, error)
}

var _ Querier = (*Queries)(nil)
