// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package collectionstore

import (
	"context"
)

type Querier interface {
	Count(ctx context.Context, userID uint64) (int64, error)
	Delete(ctx context.Context, arg DeleteParams) (Collection, error)
	Get(ctx context.Context, arg GetParams) (GetRow, error)
	GetByID(ctx context.Context, id int64) (Character, error)
	Give(ctx context.Context, arg GiveParams) (Collection, error)
	Insert(ctx context.Context, arg InsertParams) (Collection, error)
	List(ctx context.Context, userID uint64) ([]ListRow, error)
	ListIDs(ctx context.Context, userID uint64) ([]int64, error)
	// Dynamic query using squirrel query builder - called via ListPaginatedDynamic method
	// This is a placeholder for sqlc generation, actual query built dynamically
	ListPaginated(ctx context.Context, userID uint64) ([]ListPaginatedRow, error)
	SearchCharacters(ctx context.Context, arg SearchCharactersParams) ([]SearchCharactersRow, error)
	SearchGlobalCharacters(ctx context.Context, arg SearchGlobalCharactersParams) ([]Character, error)
	UpdateImageName(ctx context.Context, arg UpdateImageNameParams) (Character, error)
	UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (Character, error)
	UsersOwningCharFiltered(ctx context.Context, arg UsersOwningCharFilteredParams) ([]uint64, error)
}

var _ Querier = (*Queries)(nil)
