// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wishliststore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID    int64
	Name  string
	Image string
}

type CharacterWishlist struct {
	UserID      uint64
	CharacterID int64
	CreatedAt   pgtype.Timestamp
}

type Collection struct {
	UserID      uint64
	CharacterID int64
	Source      string
	AcquiredAt  pgtype.Timestamp
}

type GuildMember struct {
	GuildID   uint64
	UserID    uint64
	IndexedAt pgtype.Timestamp
}
