// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wishliststore

import (
	"context"
)

type Querier interface {
	AddCharactersToWishlist(ctx context.Context, arg AddCharactersToWishlistParams) error
	CompareWithUser(ctx context.Context, arg CompareWithUserParams) ([]CompareWithUserRow, error)
	GetUserCharacterWishlist(ctx context.Context, userID uint64) ([]GetUserCharacterWishlistRow, error)
	GetWantedCharacters(ctx context.Context, arg GetWantedCharactersParams) ([]GetWantedCharactersRow, error)
	GetWishlistHolders(ctx context.Context, arg GetWishlistHoldersParams) ([]GetWishlistHoldersRow, error)
	RemoveAllFromWishlist(ctx context.Context, userID uint64) error
	RemoveCharactersFromWishlist(ctx context.Context, arg RemoveCharactersFromWishlistParams) error
}

var _ Querier = (*Queries)(nil)
