// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wishliststore

import (
	"context"
)

type Querier interface {
	AddCharacterToWishlist(ctx context.Context, arg AddCharacterToWishlistParams) error
	AddMultipleCharactersToWishlist(ctx context.Context, arg AddMultipleCharactersToWishlistParams) error
	CompareWithUser(ctx context.Context, arg CompareWithUserParams) ([]CompareWithUserRow, error)
	GetUserCharacterWishlist(ctx context.Context, userID uint64) ([]GetUserCharacterWishlistRow, error)
	GetWantedCharacters(ctx context.Context, userID uint64) ([]GetWantedCharactersRow, error)
	GetWishlistHolders(ctx context.Context, arg GetWishlistHoldersParams) ([]GetWishlistHoldersRow, error)
	RemoveCharacterFromWishlist(ctx context.Context, arg RemoveCharacterFromWishlistParams) error
	RemoveMultipleCharactersFromWishlist(ctx context.Context, arg RemoveMultipleCharactersFromWishlistParams) error
}

var _ Querier = (*Queries)(nil)
