// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Character struct {
	ID     int64          `json:"id"`
	UserID int64          `json:"user_id"`
	Image  sql.NullString `json:"image"`
	Name   sql.NullString `json:"name"`
}

type User struct {
	ID         int64         `json:"id"`
	Quote      string        `json:"quote"`
	Date       time.Time     `json:"date"`
	Favorite   sql.NullInt64 `json:"favorite"`
	ClaimCount int32         `json:"claim_count"`
}
