// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Character struct {
	UserID uint64
	ID     int64
	Image  string
	Name   string
	Date   time.Time
	Type   string
}

type User struct {
	ID       int32
	UserID   uint64
	Quote    string
	Date     time.Time
	Favorite sql.NullInt64
	Tokens   int32
}
