CREATE TABLE public.sessions (
    token CHARACTER VARYING(64) PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() + INTERVAL '7 days') NOT NULL
);
