name: Build Image

on:
  push:
    tags:
      - "*"
jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: karitham
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ghcr.io/karitham/waifubot:${{ github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/karitham/waifubot:buildcache
          cache-to: type=registry,ref=ghcr.io/karitham/waifubot:buildcache,mode=max
