name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build Image"
    types:
      - completed

jobs:
  run:
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          docker-compose -f docker-compose.deploy.yml pull
          docker-compose -f docker-compose.deploy.yml up -d --remove-orphans
