name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build Image"
    types:
      - completed

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: build
        run: |
          docker-compose --env-file ~/.env.waifubot -f docker-compose.deploy.yml pull
          docker-compose --env-file ~/.env.waifubot -f docker-compose.deploy.yml up -d --remove-orphans
