name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build Image"
    types:
      - completed

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Copy config
        run: cp ~/.env.waifubot .env

      - name: build
        run: |
          docker-compose pull
          docker-compose up -d --remove-orphans
